### ISSUE TITLE
Backend Error: Latest Commit dated 23 Jan

### ISSUE THREAD

**Issue by abhayca** [sysgears/apollo-universal-starter-kit#1012]
Error running the latest commit:
`
backend error TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type undefined
    at Hmac.update (internal/crypto/hash.js:58:11)
    at hmac (/home/cool/Project/apollo-universal-starter-kit/node_modules/@module/user-server-ts/access/session/crypto.js:11:1)
    at decryptSession (/home/cool/Project/apollo-universal-starter-kit/node_modules/@module/user-server-ts/access/session/crypto.js:32:1)
    at readSession (/home/cool/Project/apollo-universal-starter-kit/node_modules/@module/user-server-ts/access/session/sessions.js:19:1)
    at attachSession (/home/cool/Project/apollo-universal-starter-kit/node_modules/@module/user-server-ts/access/session/index.js:28:1)
    at _callee3$ (/home/cool/Project/apollo-universal-starter-kit/node_modules/@module/user-server-ts/access/session/index.js:43:1)
    at tryCatch (/home/cool/Project/apollo-universal-starter-kit/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/cool/Project/apollo-universal-starter-kit/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/home/cool/Project/apollo-universal-starter-kit/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/home/cool/Project/apollo-universal-starter-kit/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/cool/Project/apollo-universal-starter-kit/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /home/cool/Project/apollo-universal-starter-kit/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at /home/cool/Project/apollo-universal-starter-kit/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
    at createContextFunc (/home/cool/Project/apollo-universal-starter-kit/node_modules/@module/user-server-ts/access/session/index.js:42:1)
    at ServerModule.<anonymous> (/home/cool/Project/apollo-universal-starter-kit/node_modules/@module/module-server-ts/ServerModule.ts:50:1)
    at step (/home/cool/Project/apollo-universal-starter-kit/packages/server/build/index.js:7981:23)
    at Object.next (/home/cool/Project/apollo-universal-starter-kit/packages/server/build/index.js:7962:53)
    at fulfilled (/home/cool/Project/apollo-universal-starter-kit/packages/server/build/index.js:7953:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`

**Comment by vlasenko** [comment]
@abhayca Thanks for reporting, but we regard such reports as invalid, because of no reproduction steps

**Comment by abhayca** [comment]
I just ran 
a. yarn
b. yarn seed
c. yarn watch

The error occurred while running yarn watch

**Comment by vlasenko** [comment]
How it runs on Heroku then?
https://apollo-universal-starter-kit.herokuapp.com/

**Comment by abhayca** [comment]
web-webpack info Webpack dev server listening on http://localhost:3000
web-webpack debug waiting for tcp:localhost:8080
backend info API is now running on port 8080
web-webpack debug Backend has been started, resuming webpack dev server...
No type errors found
Version: typescript 3.2.4
Time: 6941ms
web-webpack debug bundle is now VALID.
web-webpack info Time: 7933ms
Built at: 01/23/2019 3:27:20 PM
Entrypoint index [big] = index.6e1fc99b7ba4c4bde1b1.js index.6e1fc99b7ba4c4bde1b1.js.map
backend error TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type undefined
    at Hmac.update (internal/crypto/hash.js:58:11)

**Comment by abhayca** [comment]
Okay I'll install it again and run. Will let you know.

Thanks

**Comment by vlasenko** [comment]
Do you have this line in your cloned repo?
https://github.com/sysgears/apollo-universal-starter-kit/blob/master/packages/server/.env#L14

**Comment by vlasenko** [comment]
I have just tried to do fresh clone of `master`, then `yarn`, `yarn seed`, `yarn watch` - backend works for me

**Comment by abhayca** [comment]
yes i have this line and therefore yarn seed ran successfully.

I reinstalled and ran it but the same error.

**Comment by vlasenko** [comment]
this line has nothing to do with `yarn seed` - this line directly connected with the stacktrace of backend that you have

**Comment by vlasenko** [comment]
insert a bunch of console.log into relevant lines of `session/crypto.js` to figure out whats wrong

**Comment by abhayca** [comment]
okay . Any other hint so that I should be able to run it.

**Comment by abhayca** [comment]
okay fine

**Comment by vlasenko** [comment]
@abhayca Actually yes, I think this is the problem with the code of the kit, it fails, because you have auth cookie in the format, that it doesn't understand. To overcome this problem you can clear cookies in the browser and then restart backend
