### ISSUE TITLE
Erratic EADDRINUSE error on hot reload, old server not closed properly.

### ISSUE THREAD

**Issue by eric-burel** [sysgears/apollo-universal-starter-kit#1107]
**Describe the bug**
When modyfing a part of the code (either the js server or the web client), the Node server reload fails with error EADDRINUSE
**To Reproduce**
Just install the app on `stable` branch, run `yarn watch`, and modify some code.
However, this only happens on certain machine, in my case, my slower computer. This also can happen if some part of the code is failing due to an error.

**Expected behavior**
Shoud hot reload

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser : Chromium
- Node 10.0.0

However the setup is irrelevant, I have 2 machine with the same setup, one is affected, the other is not.
**Additional info **
The issue seems to be in the `server.ts` file.
On the failing machine, the `module.hot.dispose` callback is never called, so the server is not closed and the `server` variable not destroyed.

However, when `createServer` is run again to reload the server, `server` is now `undefined`. I can't tell which part of the code destroyed this variable, it behaves as if the new call was from a fresh instance of the app.

Therefore, it fails listening to `localhost:8080`, because the old server is still running somewhere. Here the Node server fails.

**Logs**
I've added a few more console.log in `server.ts` to track callbacks.

When running `yarn watch`:
```
yarn watch
yarn run v1.12.3
$ zen watch
zen info Version 0.1.22
clean-webpack-plugin: /home/eric-burel/Development_2018/vos-talents-dexperts/packages/server/build has been removed.
clean-webpack-plugin: /home/eric-burel/Development_2018/vos-talents-dexperts/packages/client/build has been removed.
Starting type checking service...
Using 1 worker with 2048MB memory limit
[HPM] Proxy created: !(/sockjs-node/**/*|/*.hot-update.{json,js})  ->  http://localhost:8080
server-webpack info Spawning node /home/eric-burel/Development_2018/vos-talents-dexperts/packages/server/build/index.js, env: { LAST_EXIT_CODE: 0 }
server-webpack info Time: 27921ms
Built at: 2019-06-14 14:40:00
Entrypoint index [big] = index.js index.0f2229c9bebe0625df8b.js.map
setting up module.hot.dispose callback
checking if server is defined, server: undefined
server was undefined, calling http.createServer()
backend info API is now running on port 8080
No type errors found
Version: typescript 3.4.5
Time: 36634ms
open: true
web-webpack info Time: 37219ms
Built at: 2019-06-14 14:40:12
Entrypoint index [big] = index.0bd99b5bd7f26d833b5a.js index.0bd99b5bd7f26d833b5a.js.map
```
 So far so good.
After modifying counter model (adding a simple console.log to `counterQuery`):
```
server-webpack info Time: 2115ms
Built at: 2019-06-14 14:40:40
Entrypoint index [big] = index.js index.1c0e3faf3c0bdc68777b.hot-update.js index.22bfa54c721a8c269ec0.js.map index.22bfa54c721a8c269ec0.js.map
server-webpack info Backend stopped, exit code: null
server-webpack info Spawning node /home/eric-burel/Development_2018/vos-talents-dexperts/packages/server/build/index.js, env: { LAST_EXIT_CODE: null }
setting up module.hot.dispose callback
checking if server is defined, server: undefined
server was undefined, calling http.createServer()
backend error { Error: listen EADDRINUSE :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1330:14)
    at listenInCluster (net.js:1378:12)
    at Server.listen (net.js:1466:7)
    at createServer (/home/eric-burel/Development_2018/vos-talents-dexperts/packages/server/build/index.js:4498:20)
    at onAppCreate.forEach.callback (/home/eric-burel/Development_2018/vos-talents-dexperts/packages/server/build/index.js:8797:50)
    at Array.forEach (<anonymous>)
    at ServerModule.createApp (/home/eric-burel/Development_2018/vos-talents-dexperts/packages/server/build/index.js:8797:30)
    at Module.<anonymous> (/home/eric-burel/Development_2018/vos-talents-dexperts/packages/server/build/index.js:23988:50)
    at Module../src/index.ts (/home/eric-burel/Development_2018/vos-talents-dexperts/packages/server/build/index.js:23991:30)
    at __webpack_require__ (/home/eric-burel/Development_2018/vos-talents-dexperts/packages/server/build/index.js:684:30)
    at fn (/home/eric-burel/Development_2018/vos-talents-dexperts/modules/look/client-react/index.ts:1:1)
    at Object.0 (/home/eric-burel/Development_2018/vos-talents-dexperts/packages/server/build/index.js:24051:18)
    at __webpack_require__ (/home/eric-burel/Development_2018/vos-talents-dexperts/packages/server/build/index.js:684:30)
    at /home/eric-burel/Development_2018/vos-talents-dexperts/packages/server/build/index.js:751:37
    at Object.<anonymous> (/home/eric-burel/Development_2018/vos-talents-dexperts/packages/server/build/index.js:754:10)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 8080 }
server-webpack info Backend stopped, exit code: 1
```

I'll try to post the logs of a non failing machine to check what's the expected behaviour, but basically I should have normal hot reload logs.

**Comment by vlasenko** [comment]
@eric-burel Thank you for the report. Please attach terminal output the error and like 10 lines before the error

**Comment by vlasenko** [comment]
@eric-burel What version of yarn do you use? Maybe you have this problem?:
https://github.com/sysgears/apollo-universal-starter-kit/issues/938

**Comment by eric-burel** [comment]
It's edited with the full logs of first run (ok, no error so nothing fancy in it) + then failure after a trivial file update. Will try to post the same logs for a working instance.

**Comment by eric-burel** [comment]
Good catch, `1.12.3`. Will upgrade yarn and tell you.

**Comment by eric-burel** [comment]
Solved thanks a lot! The issue does not appear with yarn 1.16.x
