### ISSUE TITLE
Installation: SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by vadimderkach** [sysgears/apollo-universal-starter-kit#1140]
**Describe the bug**
Unable to install on Windows 10

**To Reproduce**
1. git clone -b stable https://github.com/sysgears/apollo-universal-starter-kit.git myApp
2. cd myApp
3. Run "Yarn" "SyntaxError: Unexpected identifier"

**Screenshots**
```
D:\Dev\myApp>yarn
yarn install v1.17.3
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "graphql@14.3.1" is incompatible with requested version "graphql@0.13.2"
[3/5] Fetching packages...
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "expo-module-scripts > @babel/cli@7.2.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > ts-jest@23.10.5" has unmet peer dependency "jest@>=22 <24".
warning "expo-module-scripts > babel-preset-expo > @babel/plugin-proposal-decorators@7.3.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset@0.49.2" has unmet peer dependency "@babel/core@*".
warning "expo-module-scripts > jest-expo > react-test-renderer@16.8.4" has unmet peer dependency "react@^16.0.0".
warning "expo-module-scripts > babel-preset-expo > @babel/plugin-proposal-decorators > @babel/helper-create-class-features-plugin@7.3.4" has unmet peer dependency "@babel/core@^7.0.0".
warning "expo-module-scripts > babel-preset-expo > @babel/plugin-proposal-decorators > @babel/plugin-syntax-decorators@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-proposal-class-properties@7.3.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-proposal-export-default-from@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-proposal-nullish-coalescing-operator@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-proposal-object-rest-spread@7.3.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-proposal-optional-catch-binding@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-proposal-optional-chaining@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-syntax-dynamic-import@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-syntax-export-default-from@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-arrow-functions@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-block-scoping@7.3.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-classes@7.3.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-computed-properties@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-destructuring@7.3.2" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-exponentiation-operator@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-flow-strip-types@7.3.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-for-of@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-function-name@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-literals@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-modules-commonjs@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-object-assign@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-parameters@7.3.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-react-display-name@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-react-jsx@7.3.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-react-jsx-source@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-regenerator@7.3.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-runtime@7.3.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-shorthand-properties@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-spread@7.2.2" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-sticky-regex@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-template-literals@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-typescript@7.3.2" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-unicode-regex@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-proposal-nullish-coalescing-operator > @babel/plugin-syntax-nullish-coalescing-operator@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-proposal-object-rest-spread > @babel/plugin-syntax-object-rest-spread@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-proposal-optional-catch-binding > @babel/plugin-syntax-optional-catch-binding@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-proposal-optional-chaining > @babel/plugin-syntax-optional-chaining@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-flow-strip-types > @babel/plugin-syntax-flow@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-react-jsx > @babel/plugin-syntax-jsx@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo-module-scripts > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-transform-typescript > @babel/plugin-syntax-typescript@7.3.3" has unmet peer dependency "@babel/core@^7.0.0-0".
[4/4] Building fresh packages...
$ expo-module prepare && npm run generate-lazy && npm run copy-vendor
C:\Users\me\AppData\Local\Yarn\Cache\v4\.tmp\775e8647b2c2fe2a5f4e27e4331a37b9.91b400b4926eecc41a317e8854b0d45c1585674f.prepare\node_modules\expo-module-scripts\bin\expo-module-prepare:3
set -eo pipefail
        ^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version	10.0.17763 Build 17763

**Comment by vlasenko** [comment]
@vadimderkach Thank you for this issue. Could you try latest `stable` branch and confirm whether this issue has been fixed or not?

**Comment by vadimderkach** [comment]
Fixed, Thank you!

**Comment by bombillazo** [comment]
Im getting this error on an unrelated dependency, but how was this fixed or is the cause of it known?

**Comment by luismasuarez** [comment]
I have solved this problem by deleting the .gradle folder that is generated when running yarn android
