### ISSUE TITLE
lerna stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by lokeshrana9999** [sysgears/apollo-universal-starter-kit#1197]
**Describe the bug**
lerna stdout maxBuffer exceeded 
**Error Log**
nodejs-starter-kit | lerna ERR! MaxBufferError: stdout maxBuffer exceeded
nodejs-starter-kit | lerna ERR!     at PassThrough.stream.on (/usr/src/app/node_modules/get-stream/index.js:41:19)
nodejs-starter-kit | lerna ERR!     at PassThrough.emit (events.js:194:15)
nodejs-starter-kit | lerna ERR!     at addChunk (_stream_readable.js:284:12)
nodejs-starter-kit | lerna ERR!     at readableAddChunk (_stream_readable.js:261:13)
nodejs-starter-kit | lerna ERR!     at PassThrough.Readable.push (_stream_readable.js:220:10)
nodejs-starter-kit | lerna ERR!     at PassThrough.Transform.push (_stream_transform.js:151:32)
nodejs-starter-kit | lerna ERR!     at PassThrough.afterTransform (_stream_transform.js:92:10)
nodejs-starter-kit | lerna ERR!     at PassThrough._transform (_stream_passthrough.js:42:3)
nodejs-starter-kit | lerna ERR!     at PassThrough.Transform._read (_stream_transform.js:190:10)
nodejs-starter-kit | lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
nodejs-starter-kit | lerna ERR! lerna stdout maxBuffer exceeded
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Desktop :**
All devices, ps I don't think browser matters in this situation

**Additional context**
I have a complex page that quries different kinds of data from backend buf after the app runs for a while, the above error shows up, I read related issues on lerna repo, most of them point to upgrading lerna or its dependency execa but they don't seem to solve the problem. It even persists after passing max-buffer=[some large memory] after yarn watch in package.json.

### Is There a way to increase stdout and stderr maxBuffer sizes for the lerna run operations for yarn watch and yarn build? 
@larixer any help would be appreciated.

Thank you for your help!

**Comment by lokeshrana9999** [comment]
@larixer, Is there a way to deal with large logs, specially big queries without running into above problem.

**Comment by larixer** [comment]
@lokeshrana9999 I'm not aware of this problem to be fair, and have no idea what is "lerna stdout maxBuffer exceeded". Sounds like lerna-related problem to me

**Comment by lokeshrana9999** [comment]
@larixer, is there a way to disable query and error logs in apollo starter kit, might give me some breathing room to figure it out.

**Comment by larixer** [comment]
@lokeshrana9999 Yes, you can set 
`apolloLogging: false`
here:
https://github.com/sysgears/apollo-universal-starter-kit/blob/master/config/app.js#L7

**Comment by lokeshrana9999** [comment]
> @lokeshrana9999 Yes, you can set
> `apolloLogging: false`
> here:
> https://github.com/sysgears/apollo-universal-starter-kit/blob/master/config/app.js#L7

Thanks @larixer appreciate it. :-)

**Comment by larixer** [comment]
The PR  #1195 has been merged into `master`, we no longer use lerna

**Comment by larixer** [comment]
Sorry, we use lerna for now, but soon it will be removed in favor of built-in Yarn 2 features
