### ISSUE TITLE
Uncaught ReferenceError: Invalid left-hand side in assignment

### ISSUE THREAD

**Issue by illepic** [sysgears/apollo-universal-starter-kit#233]
I get the following clientside errors using Node 8 with either yarn 0.24.6 or NPM 5:

```
Uncaught ReferenceError: Invalid left-hand side in assignment vendor_web.1c2318c47335b58a98ed_dll.js:85946
Uncaught ReferenceError: vendor_web is not defined bundle.1e5c87ffb92ad0239cf7.js:16460
```

![2017-06-13 at 10 23 pm](https://user-images.githubusercontent.com/295127/27116635-38fd3b6e-5087-11e7-846b-05b2204ab6d0.png)

This is a fresh build with no modification to config.

**Comment by vlasenko** [comment]
@illepic Thanks. Could you update and try again now?

**Comment by illepic** [comment]
Hitting this right now.

**Comment by vlasenko** [comment]
@illepic What URL do you open in the browser?

**Comment by vlasenko** [comment]
@illepic Could you open that vendor_web.xxxx_dll.js at the offending line and tell me what is there on that line?

**Comment by illepic** [comment]
@vlasenko : we're gold! (My prior comment was just to let you know that I was pulling and reinstalling node_modules).

**Comment by illepic** [comment]
Thank you so, so much for a timely response. I'm very excited to dive into this.

**Comment by vlasenko** [comment]
Great! Thank you @illepic for reporting!

**Comment by mitjade** [comment]
Now I am getting this?

In terminal:
```
WARNING in ./~/require-dir/index.js
require.extensions is not supported by webpack. Use a loader instead.
 @ ./~/npm-check-updates/lib/versionmanager.js 7:17-39
 @ ./~/npm-check-updates/lib/npm-check-updates.js
 @ dll vendor

WARNING in ./~/require-dir/index.js
require.extensions is not supported by webpack. Use a loader instead.
 @ ./~/npm-check-updates/lib/versionmanager.js 7:17-39
 @ ./~/npm-check-updates/lib/npm-check-updates.js
 @ dll vendor

WARNING in ./~/require-dir/index.js
118:32-45 Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (/Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/webpack/lib/dependencies/CommonJsRequireContextDependency.js:27:4)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/webpack/lib/Compilation.js:672:24)
    at Compilation.finish (/Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/webpack/lib/Compilation.js:535:9)
    at /Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/webpack/lib/Compiler.js:491:16
    at /Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (/Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/webpack/lib/Compilation.js:481:11)
    at processModuleDependencies.err (/Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/webpack/lib/Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)

WARNING in ./~/require-dir/index.js
123:32-45 Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (/Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/webpack/lib/dependencies/CommonJsRequireContextDependency.js:27:4)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/webpack/lib/Compilation.js:672:24)
    at Compilation.finish (/Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/webpack/lib/Compilation.js:535:9)
    at /Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/webpack/lib/Compiler.js:491:16
    at /Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (/Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/webpack/lib/Compilation.js:481:11)
    at processModuleDependencies.err (/Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/webpack/lib/Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)

WARNING in ./~/jju/lib/utils.js
8:2-3 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
    at CommonJsRequireContextDependency.getWarnings (/Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/webpack/lib/dependencies/CommonJsRequireContextDependency.js:27:4)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/webpack/lib/Compilation.js:672:24)
    at Compilation.finish (/Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/webpack/lib/Compilation.js:535:9)
    at /Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/webpack/lib/Compiler.js:491:16
    at /Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (/Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/webpack/lib/Compilation.js:481:11)
    at processModuleDependencies.err (/Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/webpack/lib/Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)

WARNING in ./~/cli-table/~/colors/lib/colors.js
127:29-43 Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (/Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/webpack/lib/dependencies/CommonJsRequireContextDependency.js:27:4)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/webpack/lib/Compilation.js:672:24)
    at Compilation.finish (/Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/webpack/lib/Compilation.js:535:9)
    at /Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/webpack/lib/Compiler.js:491:16
    at /Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (/Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/webpack/lib/Compilation.js:481:11)
    at processModuleDependencies.err (/Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/webpack/lib/Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)

ERROR in ./~/npm-check-updates/lib/npm-check-updates.js
Module not found: Error: Can't resolve 'fs' in '/Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/npm-check-updates/lib'
resolve 'fs' in '/Users/mitjad/Sites/projects/apollo-universal-starter-kit/node_modules/npm-check-updates/lib'
  Parsed request is a module
...
```

**Comment by mitjade** [comment]
Second time I run this, browser errors remains, terminal one is gone.

To get the terminal error did delete `build` and `node_modules` dirs.

**Comment by vlasenko** [comment]
@mitjade This is because I have added `npm-check-updates` to dependencies by mistake. I have remove them in the last commit to master, please check whether you pulled this commit from master and have no `npm-check-updates` in package.json dependencies

**Comment by mitjade** [comment]
Ah. Sorry. I did but then switched to a different branch and did not merger this in.
