### ISSUE TITLE
TypeError: Cannot read property 'source' of undefined

### ISSUE THREAD

**Issue by zunder** [sysgears/apollo-universal-starter-kit#240]
Starting `npm run watch` with following settings causes a problem during source list mapping. I am only documenting my changes in settings compared to current master branch.

**app.json:**
```
{
  "app": {
    ...
    "webpackDll": true,
    "ios": true
  }
}
```

**webpack.app_config.js**:
```
const serverConfig = {
  // Uncomment the next line and set URL if you use external GraphQL server
  url: 'http://localhost:8082',
  entry: {
    ...
  }
};
```

**Terminal:**
```
> node tools/webpack.entry watch

[HPM] Proxy created: !/*.hot-update.{json,js}  ->  http://localhost:8080
webpack-for-web-frontend Webpack web-frontend dev server listening on http://localhost:3000
webpack-for-android-frontend Webpack android-frontend dev server listening on http://localhost:3010
TypeError: Cannot read property 'source' of undefined
    at /Users/user/github.com/zunder/apollo-universal-starter-kit/tools/webpack.run.js:272:26
    at arrayEach (/Users/user/github.com/zunder/apollo-universal-starter-kit/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/Users/user/github.com/zunder/apollo-universal-starter-kit/node_modules/lodash/lodash.js:9359:14)
    at /Users/user/github.com/zunder/apollo-universal-starter-kit/tools/webpack.run.js:267:11
    at arrayEach (/Users/user/github.com/zunder/apollo-universal-starter-kit/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/Users/user/github.com/zunder/apollo-universal-starter-kit/node_modules/lodash/lodash.js:9359:14)
    at Compiler.<anonymous> (/Users/user/github.com/zunder/apollo-universal-starter-kit/tools/webpack.run.js:266:9)
    at next (/Users/user/github.com/zunder/apollo-universal-starter-kit/node_modules/webpack/node_modules/tapable/lib/Tapable.js:140:14)
    at Compiler.<anonymous> (/Users/user/github.com/zunder/apollo-universal-starter-kit/node_modules/webpack/lib/CachePlugin.js:62:5)
    at Compiler.applyPluginsAsyncSeries (/Users/user/github.com/zunder/apollo-universal-starter-kit/node_modules/webpack/node_modules/tapable/lib/Tapable.js:142:13)
    at /Users/user/github.com/zunder/apollo-universal-starter-kit/node_modules/webpack/lib/Compiler.js:496:10
    at Compilation.applyPluginsAsyncSeries (/Users/user/github.com/zunder/apollo-universal-starter-kit/node_modules/webpack/node_modules/tapable/lib/Tapable.js:131:46)
    at self.applyPluginsAsync.err (/Users/user/github.com/zunder/apollo-universal-starter-kit/node_modules/webpack/lib/Compilation.js:649:19)
    at Compilation.applyPluginsAsyncSeries (/Users/user/github.com/zunder/apollo-universal-starter-kit/node_modules/webpack/node_modules/tapable/lib/Tapable.js:131:46)
    at self.applyPluginsAsync.err (/Users/user/github.com/zunder/apollo-universal-starter-kit/node_modules/webpack/lib/Compilation.js:640:11)
    at Compilation.applyPluginsAsyncSeries (/Users/user/github.com/zunder/apollo-universal-starter-kit/node_modules/webpack/node_modules/tapable/lib/Tapable.js:131:46)
webpack-for-web-frontend bundle is now VALID.
webpack-for-web-frontend Time: 7631ms
Expo address: exp://192.168.16.9:19000
To open this app on your phone scan this QR code in Expo Client (if it doesn't get started automatically)
```

**Comment by vlasenko** [comment]
@zunder Should be fixed now in `master`, please update sources and check

**Comment by zunder** [comment]
@vlasenko thank you for this one! It fixed the RN build.
