### ISSUE TITLE
Got some errors on Windows 10

### ISSUE THREAD

**Issue by MichelDiz** [sysgears/apollo-universal-starter-kit#330]
Greetins,

I'm using a Windows with clean installation. Everything installed (node, npm, yarn, pcks) correctly (I suppose) but I get this error. I just did this to get an updated code and experiences with Join Monster. But it looks like I'll have to go back there to Mac Tomorrow xD

Apparently have something to do with Babel - going to sleep / drops me

```
ERROR in ./src/server/api_server.js
Module parse failed: C:\Users\miche\Desktop\apollo-universal-starter-kit\src\server\api_server.js Unexpected token (52:12)
You may need an appropriate loader to handle this file type.
|           return {
|             query: invertedMap[body.id],
|             ...body
|           };
|         });
 @ ./src/server/index.js 2:0-22
 @ multi ./src/server/index.js

ERROR in index.js from UglifyJs
Unexpected token: name (console_log) [index.js:92,6]
```

After that I made a new attempt (Windows)

```
yarn watch v0.27.5
$ spin watch
TypeError: stack.hasAll is not a function
    at WebAssetsPlugin.configure (C:\Users\miche\Desktop\apiJoinMonster\node_modules\spinjs\src\plugins\WebAssetsPlugin.ts:9:19)
    at C:\Users\miche\Desktop\apiJoinMonster\node_modules\spinjs\src\spin.config.ts:68:69
    at Array.forEach (<anonymous>)
    at _loop_1 (C:\Users\miche\Desktop\apiJoinMonster\node_modules\spinjs\src\spin.config.ts:68:28)
    at createConfig (C:\Users\miche\Desktop\apiJoinMonster\node_modules\spinjs\lib\spin.config.js:75:13)
    at Object.exports.default (C:\Users\miche\Desktop\apiJoinMonster\node_modules\spinjs\src\createConfig.ts:11:12)
    at Object.<anonymous> (C:\Users\miche\Desktop\apiJoinMonster\node_modules\spinjs\src\index.ts:18:26)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
TypeError: Cannot read property 'name' of undefined
    at C:\Users\miche\Desktop\apiJoinMonster\node_modules\spinjs\src\executor.ts:552:53
    at Promise (<anonymous>)
    at buildDll (C:\Users\miche\Desktop\apiJoinMonster\node_modules\spinjs\src\executor.ts:550:12)
    at _loop_1 (C:\Users\miche\Desktop\apiJoinMonster\node_modules\spinjs\src\executor.ts:786:21)
    at C:\Users\miche\Desktop\apiJoinMonster\node_modules\spinjs\lib\executor.js:849:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:611:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
webpack-for-server Time: 164ms

ERROR in ./src/server/api_server.js
Module parse failed: C:\Users\miche\Desktop\apiJoinMonster\src\server\api_server.js Unexpected token (52:12)
You may need an appropriate loader to handle this file type.
|           return {
|             query: invertedMap[body.id],
|             ...body
|           };
|         });
 @ ./src/server/index.js 2:0-22
 @ multi ./src/server/index.js webpack/hot/poll?1000
```

**Comment by mitjade** [comment]
@MichelDiz I might have broken something when accidentally merging one of the branches. Please wait for @vlasenko to check it out.

**Comment by mitjade** [comment]
I have the same problem and am investigating.

**Comment by mitjade** [comment]
@MichelDiz Moving back to Commit: 8167a374f67452a4456a2f7e282c23d3ea60d344`Specify safe version of Yarn for Heroku` Seems to work. Might be a problem with `spinjs`.

**Comment by mitjade** [comment]
@vlasenko If I move to `spinjs` branch, this starts happening with 8ed1572af65db2c7b40431fa0e4c666b6e95eed8 `Update to the latest spin.js version`. Commit before is ok.

I do a:
```
rm -rf node_modules/
rm -rf build/
yarn install
yarn watch
```

**Comment by vlasenko** [comment]
@MichelDiz Please try with the latest sources of the kit, or update version of `spinjs` to `0.2.0` in `package.json`

**Comment by mitjade** [comment]
@vlasenko could you also commit `yarn.lock`?

**Comment by vlasenko** [comment]
@mitjade Yep, done, thanks for noticing
