### ISSUE TITLE
flow-typed folder

### ISSUE THREAD

**Issue by mairh** [sysgears/apollo-universal-starter-kit#362]
Do I need to manually add the `flow-typed` folder (at root level) in my personal fork or can I auto-generate the folder using come script/command?

**Comment by vlasenko** [comment]
@mairh You can generate it as described by Mitja

**Comment by mairh** [comment]
Am I doing anything wrong?

![screen shot 2017-09-19 at 13 38 20](https://user-images.githubusercontent.com/4072250/30588567-d9422328-9d3f-11e7-94c2-5d5ba029105e.png)

**Comment by mairh** [comment]
ok. got it. The correct command is 

```
yarn global  flow-typed
flow-typed install
```

Note: `global` should be before `add`

**Comment by mairh** [comment]
Is this expected after running the above command?

![screen shot 2017-09-19 at 13 48 56](https://user-images.githubusercontent.com/4072250/30588952-671c2dd2-9d41-11e7-898e-465e8402e977.png)
![screen shot 2017-09-19 at 13 49 08](https://user-images.githubusercontent.com/4072250/30588962-6c796e48-9d41-11e7-8c31-38ba37b2e8ef.png)

**Comment by vlasenko** [comment]
@mairh Yes, it is expected

**Comment by mairh** [comment]
I just added flow to my personal fork according to this commit https://github.com/sysgears/apollo-universal-starter-kit/pull/361/commits/271199a34b59e0d2eba4c49a8186e7e457909734 and replaced the `server/modules/connector.js` file with the one in latest master and I'm getting this error

```
/Users/nish/Documents/code/EasyMedi/node_modules/tcomb/lib/fail.js:2
  throw new TypeError('[tcomb] ' + message);
        ^
TypeError: [tcomb] Invalid value {
  "publish": "publish",
  "subscribe": "subscribe",
  "unsubscribe": "unsubscribe",
  "asyncIterator": "asyncIterator"
} supplied to pubsub (expected a PubSub)
    at Function.fail (/Users/nish/Documents/code/EasyMedi/node_modules/tcomb/lib/fail.js:2:9)
    at _assert (/Users/nish/Documents/code/EasyMedi/build/server/index.js:15074:51)
    at Feature.createResolvers (/Users/nish/Documents/code/EasyMedi/src/server/modules/connector.js:44:1)
    at Object../src/server/api/schema.js (/Users/nish/Documents/code/EasyMedi/src/server/api/schema.js:14:1)
    at __webpack_require__ (/Users/nish/Documents/code/EasyMedi/webpack/bootstrap 991272b68b50085657a4:637:1)
    at fn (/Users/nish/Documents/code/EasyMedi/webpack/bootstrap 991272b68b50085657a4:47:1)
    at Object../src/server/middleware/graphql.js (/Users/nish/Documents/code/EasyMedi/build/server/index.js:14480:70)
    at __webpack_require__ (/Users/nish/Documents/code/EasyMedi/webpack/bootstrap 991272b68b50085657a4:637:1)
    at fn (/Users/nish/Documents/code/EasyMedi/webpack/bootstrap 991272b68b50085657a4:47:1)
    at Object../src/server/api_server.js (/Users/nish/Documents/code/EasyMedi/build/server/index.js:14236:79)
    at __webpack_require__ (/Users/nish/Documents/code/EasyMedi/webpack/bootstrap 991272b68b50085657a4:637:1)
    at fn (/Users/nish/Documents/code/EasyMedi/webpack/bootstrap 991272b68b50085657a4:47:1)
    at Object../src/server/index.js (/Users/nish/Documents/code/EasyMedi/src/server/index.js:1:1)
    at __webpack_require__ (/Users/nish/Documents/code/EasyMedi/webpack/bootstrap 991272b68b50085657a4:637:1)
    at fn (/Users/nish/Documents/code/EasyMedi/webpack/bootstrap 991272b68b50085657a4:47:1)
    at Object.0 (/Users/nish/Documents/code/EasyMedi/build/server/index.js:18678:1)
webpack-for-server Backend has been stopped
```
![screen shot 2017-09-19 at 13 57 08](https://user-images.githubusercontent.com/4072250/30589599-be8b497a-9d43-11e7-9d0a-acbc8ace0071.png)


Not sure what is wrong since it is such a small change.

**Comment by vlasenko** [comment]
@mairh Difficult to say what is wrong. I recommend to just replace type of `pubsub` argument in `server/modules/connector.js` to `any`

**Comment by mairh** [comment]
Replacing it with `any` works fine.  I will close this issue.
