### ISSUE TITLE
Migrating to ApolloV2

### ISSUE THREAD

**Issue by mairh** [sysgears/apollo-universal-starter-kit#381]
I just tried migrating to new Apollo V2 and I started to get the following error in my personal fork. I wasn't facing this issue before the migration. Do you have any idea if there is any new setting on the payload size in Apollo V2

**On Brower console**

<img width="857" alt="screen shot 2017-09-22 at 16 27 27" src="https://user-images.githubusercontent.com/4072250/30746618-00110c60-9fb3-11e7-9b16-8ec9438fe151.png">

**In Terminal**
```
PayloadTooLargeError: request entity too large
    at readStream (/Users/nish/Documents/code/EasyMedi/node_modules/raw-body/index.js:155:17)
    at getRawBody (/Users/nish/Documents/code/EasyMedi/node_modules/raw-body/index.js:108:12)
    at read (/Users/nish/Documents/code/EasyMedi/node_modules/body-parser/lib/read.js:77:3)
    at jsonParser (/Users/nish/Documents/code/EasyMedi/node_modules/body-parser/lib/types/json.js:134:5)
    at Layer.handle [as handle_request] (/Users/nish/Documents/code/EasyMedi/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nish/Documents/code/EasyMedi/node_modules/express/lib/router/index.js:317:13)
    at /Users/nish/Documents/code/EasyMedi/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/nish/Documents/code/EasyMedi/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nish/Documents/code/EasyMedi/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/Users/nish/Documents/code/EasyMedi/node_modules/body-parser/lib/types/urlencoded.js:100:7)
    at Layer.handle [as handle_request] (/Users/nish/Documents/code/EasyMedi/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nish/Documents/code/EasyMedi/node_modules/express/lib/router/index.js:317:13)
    at /Users/nish/Documents/code/EasyMedi/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/nish/Documents/code/EasyMedi/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nish/Documents/code/EasyMedi/node_modules/express/lib/router/index.js:275:10)
    at cors (/Users/nish/Documents/code/EasyMedi/node_modules/cors/lib/index.js:188:7)
```

Although the error seems to point at `body-parser` I just wonder why it wasn't showing up before Apollo V2?

**Comment by vlasenko** [comment]
I'm not sure why `payload` hits limit with Apollo V2. Maybe try increasing limit in `src/server/server.js`?
`app.use(bodyParser({limit: '50mb'}));`

**Comment by mairh** [comment]
I updated the screenshot of browser console too.

**Comment by vlasenko** [comment]
@mairh Could you try to examine HTTP requests in browser dev tools network tab?

**Comment by mairh** [comment]
This is what I'm getting

<img width="856" alt="screen shot 2017-09-22 at 16 33 20" src="https://user-images.githubusercontent.com/4072250/30746840-ded62c32-9fb3-11e7-805f-4e2b53681001.png">

<img width="854" alt="screen shot 2017-09-22 at 16 34 07" src="https://user-images.githubusercontent.com/4072250/30746842-e3128ae8-9fb3-11e7-8e57-f1bbff7af051.png">

**Comment by mairh** [comment]
So, changing the following lines works.

```
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
```

```
app.use(bodyParser.urlencoded({ limit: '50mb', extended: true, parameterLimit: 50000 }));
app.use(bodyParser.json({ limit: '50mb' }));
```

I believe somehow Apollo is not able to send a large amount of data in one request. For e.g in the kit, we have (Post and Comment component/data in the edit view) example. But in my personal fork I have (Order, Product, Comment components in the edit view). Thus, I am rendering a bit more data.

Shall we make this change in the kit?

**Comment by vlasenko** [comment]
@mairh Yes, sure, could you prepare PR?

**Comment by vlasenko** [comment]
@mairh Or just commit directly if you want

**Comment by mairh** [comment]
I'll push to the master

**Comment by vlasenko** [comment]
@mairh Apparently PayloadTooLargeError was a bug in early Apollo Beta versions. It should be fixed now and should not require increasing bodyParser limit.

**Comment by mairh** [comment]
@vlasenko So shall we revert back the changes?

**Comment by vlasenko** [comment]
@mairh Yes
