### ISSUE TITLE
[Postgres] 'yarn rollback' causes drop "post" and "user" table errors. 

### ISSUE THREAD

**Issue by JoeNoPhoto** [sysgears/apollo-universal-starter-kit#450]
When using a postgres db, the following error occurs during the rollback:
```
💣  yarn rollback
yarn run v1.2.1
$ knex migrate:rollback
Using environment: development
Knex:warning - migrations failed with error: drop table "post" - cannot drop table post because other objects depend on it
error: cannot drop table post because other objects depend on it
    at Connection.parseE (/Users/JoeNoPhoto/Projects/apollo-universal-starter-kit/node_modules/pg/lib/connection.js:546:11)
    at Connection.parseMessage (/Users/JoeNoPhoto/Projects/apollo-universal-starter-kit/node_modules/pg/lib/connection.js:371:19)
    at Socket.<anonymous> (/Users/JoeNoPhoto/Projects/apollo-universal-starter-kit/node_modules/pg/lib/connection.js:114:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:264:12)
    at readableAddChunk (_stream_readable.js:251:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread (net.js:587:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

There's an identical error appears for "user". I was able to fix it by swapping the "post" and "user" dropTable(s) to the end of their respective exports.down Promises:

**migrations/003_post.js:**
```
exports.down = function(knex, Promise) {
  return Promise.all([knex.schema.dropTable('comment'), knex.schema.dropTable('post')]);
};
```
**to**
```
exports.down = function(knex, Promise) {
  return Promise.all([knex.schema.dropTable('post'), knex.schema.dropTable('comment')]);
};
```

**migrations/002_user.js**
```
exports.down = function(knex, Promise) {
  return Promise.all([
    knex.schema.dropTable('user')
    knex.schema.dropTable('auth_local'),
    knex.schema.dropTable('auth_certificate'),
    knex.schema.dropTable('auth_facebook'),
  ]);
};
```
**to**
```
exports.down = function(knex, Promise) {
  return Promise.all([
    knex.schema.dropTable('auth_local'),
    knex.schema.dropTable('auth_certificate'),
    knex.schema.dropTable('auth_facebook'),
    knex.schema.dropTable('user')
  ]);
};
```

**Comment by mitjade** [comment]
@JoeNoPhoto Thank you for reporting the issue and providing a fix! Would you be willing to make a PR for this?

**Comment by JoeNoPhoto** [comment]
There we go.

**Comment by mitjade** [comment]
@JoeNoPhoto Merged! Thank you for your help.
