### ISSUE TITLE
Cannot run project

### ISSUE THREAD

**Issue by josephdburdick** [sysgears/apollo-universal-starter-kit#479]
Hello, I've been keeping up with the project and wanted to give the auth/admin stuff a test run but couldn't run anything.

Here's the output trying to run `yarn seed`:

```
❯ yarn seed
yarn run v1.2.1
$ npm run migrate && knex seed:run
npm info it worked if it ends with ok
npm info using npm@5.5.1
npm info using node@v8.1.4
npm info lifecycle apollo-universal-starter-kit@1.0.0~premigrate: apollo-universal-starter-kit@1.0.0
npm info lifecycle apollo-universal-starter-kit@1.0.0~migrate: apollo-universal-starter-kit@1.0.0

> apollo-universal-starter-kit@1.0.0 migrate /Users/jb/Projects/clones/apollo-universal-starter-kit
> knex migrate:latest

Using environment: development
Error: The migration directory is corrupt, the following files are missing: counter.js, post.js
    at validateMigrationList (/Users/jb/Projects/clones/apollo-universal-starter-kit/node_modules/knex/lib/migrate/index.js:536:11)
    at PassThroughHandlerContext.finallyHandler (/Users/jb/Projects/clones/apollo-universal-starter-kit/node_modules/bluebird/js/release/finally.js:57:23)
    at PassThroughHandlerContext.tryCatcher (/Users/jb/Projects/clones/apollo-universal-starter-kit/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jb/Projects/clones/apollo-universal-starter-kit/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jb/Projects/clones/apollo-universal-starter-kit/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jb/Projects/clones/apollo-universal-starter-kit/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jb/Projects/clones/apollo-universal-starter-kit/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/jb/Projects/clones/apollo-universal-starter-kit/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/jb/Projects/clones/apollo-universal-starter-kit/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/jb/Projects/clones/apollo-universal-starter-kit/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/Users/jb/Projects/clones/apollo-universal-starter-kit/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/jb/Projects/clones/apollo-universal-starter-kit/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jb/Projects/clones/apollo-universal-starter-kit/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/jb/Projects/clones/apollo-universal-starter-kit/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/jb/Projects/clones/apollo-universal-starter-kit/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/jb/Projects/clones/apollo-universal-starter-kit/node_modules/bluebird/js/release/async.js:17:14)
npm info lifecycle apollo-universal-starter-kit@1.0.0~migrate: Failed to exec migrate script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! apollo-universal-starter-kit@1.0.0 migrate: `knex migrate:latest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the apollo-universal-starter-kit@1.0.0 migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jb/.npm/_logs/2017-10-30T18_05_51_285Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by vlasenko** [comment]
@josephdburdick 
``` sh
rm dev-db.sqlite3
yarn seed
```

**Comment by josephdburdick** [comment]
That worked. 👍  

Props @vlasenko and the rest of the contributors for all the progress.
