### ISSUE TITLE
yarn exp bi error

### ISSUE THREAD

**Issue by krzysztofp** [sysgears/apollo-universal-starter-kit#491]
What am I doing wrong here?

I'm running:
$ yarn build
```
yarn build v0.27.5
$ spin build
webpack-for-ios Time: 150212ms
webpack-for-android Time: 172283ms
webpack-for-server Time: 188817ms
webpack-for-web Time: 216235ms
Done in 224.04s.
```
And then:
$ yarn exp bi
```
yarn exp v0.27.5
$ spin exp "bi"
spin error TypeError: Cannot read property 'builders' of undefined
    at Object.<anonymous> (./apollo-universal-starter-kit/node_modules/spinjs/src/index.ts:34:29)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (./apollo-universal-starter-kit/node_modules/spinjs/spin.js:4:1)
    at Module._compile (module.js:624:30)
Done in 1.25s.
```

**Comment by vlasenko** [comment]
@krzysztofp Nothing wrong, it is a bug, that should be fixed now via:
https://github.com/sysgears/apollo-universal-starter-kit/commit/092e0400e10f31f966e149b3fec6c8a3e71f2da5

**Comment by krzysztofp** [comment]
@vlasenko many thanks, works perfectly now:

$ yarn exp publish
```
yarn exp v0.27.5
$ spin exp "publish"
spin info Starting Expo prod server
spin info Production mobile packager listening on http://localhost:3030
spin info Expo server running on address: exp://localhost:19000
[exp] Publishing...
[exp] Building iOS bundle
[exp] Building Android bundle
[exp] Analyzing assets
[exp] Uploading assets
[exp] Uploading ./apollo-universal-starter-kit/kidcareshare-icon.png
[exp] Uploading JavaScript bundles
[exp] Published
[exp] Your URL is

https://exp.host/@username/appname

Done in 20.76s.
```
$ yarn exp bi
```
yarn exp v0.27.5
$ spin exp "bi"
spin info Starting Expo prod server
spin info Production mobile packager listening on http://localhost:3030
spin info Expo server running on address: exp://localhost:19000
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[exp] Checking for existing Apple credentials...
[exp] Validating Apple credentials...
[exp] Credentials valid.
[exp] Validating distribution certificate...
[exp] Validating app id...
[exp] Validating push certificate...
[exp] Starting build process...
[exp] Publishing...
[exp] Building iOS bundle
[exp] Building Android bundle
[exp] Analyzing assets
[exp] Uploading assets
[exp] No assets changed, skipped.
[exp] Uploading JavaScript bundles
[exp] Published
[exp] Your URL is

https://exp.host/@username/appname

[exp] Building...
[exp] Build started, it may take a few minutes to complete.
[exp] Build ID: 55......-....-....-....-........403
[exp] Run `exp build:status` to monitor it.
Done in 39.45s.
```
