### ISSUE TITLE
Erro build / node-pre-gyp install --fallback-to-build

### ISSUE THREAD

**Issue by MichelDiz** [sysgears/apollo-universal-starter-kit#503]
System - CentOS
command = Docker-compose up

Fail.

```cmd
sudo docker-compose up
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Starting apollo_universal_starter ... 
Starting apollo_universal_starter ... done
Attaching to apollo_universal_starter
yarn install v1.3.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "antd > react-lazy-load@3.0.12" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0".
warning "antd > react-lazy-load@3.0.12" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0-0".
warning "antd > react-slick@0.15.4" has incorrect peer dependency "react@^0.14.0 || ^15.0.1".
warning "antd > react-slick@0.15.4" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.1".
warning "antd > react-slick > slick-carousel@1.8.1" has unmet peer dependency "jquery@>=1.8.0".
warning " > bootstrap@4.0.0-beta.2" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.0.0-beta.2" has unmet peer dependency "popper.js@^1.12.3".
warning " > react-native@0.49.3" has incorrect peer dependency "react@16.0.0-beta.5".
warning " > babel-loader@7.1.2" has unmet peer dependency "babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc".
warning " > haul@1.0.0-beta.10" has incorrect peer dependency "babel-preset-react-native@^2.0.0".
warning "jsdom > request-promise-native@1.0.5" has unmet peer dependency "request@^2.34".
warning "jsdom > request-promise-native > request-promise-core@1.1.1" has unmet peer dependency "request@^2.34".
warning " > mocha-webpack@0.7.0" has incorrect peer dependency "mocha@^2.4.5 || ^3.0.0".
warning " > mocha-webpack@0.7.0" has incorrect peer dependency "webpack@^1.12.13 || ^2.1.0-beta.15".
[5/5] Building fresh packages...




error /usr/src/app/node_modules/sqlite3: Command failed.
apollo_universal_starter | Exit code: 1
apollo_universal_starter | Command: node-pre-gyp install --fallback-to-build
apollo_universal_starter | Arguments: 
apollo_universal_starter | Directory: /usr/src/app/node_modules/sqlite3
apollo_universal_starter | Output:
apollo_universal_starter | node-pre-gyp info it worked if it ends with ok
apollo_universal_starter | node-pre-gyp info using node-pre-gyp@0.6.39
apollo_universal_starter | node-pre-gyp info using node@9.1.0 | linux | x64
apollo_universal_starter | node-pre-gyp info check checked for "/usr/src/app/node_modules/sqlite3/lib/binding/node-v59-linux-x64/node_sqlite3.node" (not found)
apollo_universal_starter | node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v59-linux-x64.tar.gz
apollo_universal_starter | node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v59-linux-x64.tar.gz
apollo_universal_starter | node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v59-linux-x64.tar.gz 
apollo_universal_starter | node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@9.1.0 (node-v59 ABI, musl) (falling back to source compile with node-gyp) 
apollo_universal_starter | node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v59-linux-x64.tar.gz 
apollo_universal_starter | gyp info it worked if it ends with ok
apollo_universal_starter | gyp info using node-gyp@3.6.2
apollo_universal_starter | gyp info using node@9.1.0 | linux | x64
apollo_universal_starter | gyp info ok 
apollo_universal_starter | gyp info it worked if it ends with ok
apollo_universal_starter | gyp info using node-gyp@3.6.2
apollo_universal_starter | gyp info using node@9.1.0 | linux | x64
apollo_universal_starter | gyp ERR! configure error 
apollo_universal_starter | gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
apollo_universal_starter | gyp ERR! stack     at PythonFinder.failNoPython (/usr/src/app/node_modules/node-gyp/lib/configure.js:483:19)
apollo_universal_starter | gyp ERR! stack     at PythonFinder.<anonymous> (/usr/src/app/node_modules/node-gyp/lib/configure.js:397:16)
apollo_universal_starter | gyp ERR! stack     at F (/usr/src/app/node_modules/which/which.js:68:16)
apollo_universal_starter | gyp ERR! stack     at E (/usr/src/app/node_modules/which/which.js:80:29)
apollo_universal_starter | gyp ERR! stack     at /usr/src/app/node_modules/which/which.js:89:16
apollo_universal_starter | gyp ERR! stack     at /usr/src/app/node_modules/isexe/index.js:42:5
apollo_universal_starter | gyp ERR! stack     at /usr/src/app/node_modules/isexe/mode.js:8:5
apollo_universal_starter | gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
apollo_universal_starter | gyp ERR! System Linux 3.10.0-693.5.2.el7.x86_64
apollo_universal_starter | gyp ERR! command "/usr/local/bin/node" "/usr/src/app/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/src/app/node_modules/sqlite3/lib/binding/node-v59-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/usr/src/app/node_modules/sqlite3/lib/binding/node-v59-linux-x64"
apollo_universal_starter | gyp ERR! cwd /usr/src/app/node_modules/sqlite3
apollo_universal_starter | gyp ERR! node -v v9.1.0
apollo_universal_starter | gyp ERR! node-gyp -v v3.6.2
apollo_universal_starter | gyp ERR! not ok 
apollo_universal_starter | node-pre-gyp ERR! build error 
apollo_universal_starter | node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/src/app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/src/app/node_modules/sqlite3/lib/binding/node-v59-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/src/app/node_modules/sqlite3/lib/binding/node-v59-linux-x64' (1)
apollo_universal_starter | node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/src/app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
apollo_universal_starter | node-pre-gyp ERR! stack     at emitTwo (events.js:135:13)
apollo_universal_starter | node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:224:7)
apollo_universal_starter | node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
apollo_universal_starter | node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
apollo_universal_starter | node-pre-gyp ERR! System Linux 3.10.0-693.5.2.el7.x86_64
apollo_universal_starter | node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/src/app/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
apollo_universal_starter | node-pre-gyp ERR! cwd /usr/src/app/node_modules/sqlite3
apollo_universal_starter | node-pre-gyp ERR! node -v v9.1.0
apollo_universal_starter | node-pre-gyp ERR! node-pre-gyp -v v0.6.39




apollo_universal_starter exited with code 1
```

**Comment by MichelDiz** [comment]
I was able to reproduce the error in another environment that escapes my administration and is public.

Video proof xD https://youtu.be/-Jv6keQ94i4
5:28 min
