### ISSUE TITLE
Issue trying to keep code inside container. (Moral support pls)

### ISSUE THREAD

**Issue by MichelDiz** [sysgears/apollo-universal-starter-kit#597]
I'm creating an CI/CD with Rancher and Gitlab with Rancher-gitlab-deploy. Every process is ok, the build is working perfectly. The code is correct for the Gitlab registry inside the image. But at the time of installation occurred the error below.

OBS. I'm not using Docker-compose.

List

```
7/12/2017 16:25:39CONTRIBUTING.md          config                   package.json
27/12/2017 16:25:39Dockerfile               docker-compose.prod.yml  postcss.config.js
27/12/2017 16:25:39LICENSE                  docker-compose.yml       settings.js
27/12/2017 16:25:39Procfile                 flow-typed               src
27/12/2017 16:25:39README.md                knexdata.js              tools
27/12/2017 16:25:39app.json                 knexfile.js              yarn-error.log
27/12/2017 16:25:39app.png                  logo.svg                 yarn.lock
27/12/2017 16:25:39build                    node_modules
```

```dockerfile
FROM node:9.3.0-alpine

MAINTAINER Victor Vlasenko <victor.vlasenko@sysgears.com>

RUN apk add --no-cache tini git

ARG APP_DIR

RUN mkdir -p ${APP_DIR}/build && \
    mkdir -p ${APP_DIR}/node_modules && \
    mkdir -p /home/node/.cache/yarn && \
    chown node:node -R ${APP_DIR} /home/node

WORKDIR /${APP_DIR}
COPY . /${APP_DIR}

USER node

ENTRYPOINT ["/sbin/tini", "--"]
```

```bash
27/12/2017 15:16:01yarn install v1.3.2
27/12/2017 15:16:02[1/5] Validating package.json...
27/12/2017 15:16:02[2/5] Resolving packages...
27/12/2017 15:16:03[3/5] Fetching packages...
27/12/2017 15:16:58warning "antd > rc-editor-mention@1.1.1" has unmet peer dependency "immutable@~3.7.4".
27/12/2017 15:16:58warning "antd > react-slick > slick-carousel@1.8.1" has unmet peer dependency "jquery@>=1.8.0".
27/12/2017 15:16:58warning " > bootstrap@4.0.0-beta.2" has unmet peer dependency "jquery@1.9.1 - 3".
27/12/2017 15:16:58warning " > bootstrap@4.0.0-beta.2" has unmet peer dependency "popper.js@^1.12.3".
27/12/2017 15:16:58warning "expo > react-native-maps@0.17.1" has unmet peer dependency "prop-types@^15.5.10".
27/12/2017 15:16:58warning "expo > react-native-svg@5.5.1" has unmet peer dependency "prop-types@^15.5.8".
27/12/2017 15:16:58warning " > react-ga@2.3.5" has unmet peer dependency "prop-types@^15.5.10".
27/12/2017 15:16:58warning " > react-native@0.51.0" has incorrect peer dependency "react@16.0.0".
27/12/2017 15:16:58info fsevents@1.1.3: The platform "linux" is incompatible with this module.
27/12/2017 15:16:58info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
27/12/2017 15:16:58info @expo/traveling-fastlane-darwin@1.0.15: The platform "linux" is incompatible with this module.
27/12/2017 15:16:58info "@expo/traveling-fastlane-darwin@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
27/12/2017 15:16:58[4/5] Linking dependencies...
27/12/2017 15:16:58warning " > babel-loader@7.1.2" has unmet peer dependency "babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc".
27/12/2017 15:16:58warning "exp > xdl > glob-promise@3.3.0" has unmet peer dependency "glob@*".
27/12/2017 15:16:58warning "jsdom > request-promise-native@1.0.5" has unmet peer dependency "request@^2.34".
27/12/2017 15:16:58warning " > haul@1.0.0-beta.11" has unmet peer dependency "babel-preset-react-native@^2.0.0".
27/12/2017 15:16:58warning " > mocha-webpack@0.7.0" has incorrect peer dependency "mocha@^2.4.5 || ^3.0.0".
27/12/2017 15:16:58warning " > mocha-webpack@0.7.0" has incorrect peer dependency "webpack@^1.12.13 || ^2.1.0-beta.15".
27/12/2017 15:17:51[5/5] Building fresh packages...
27/12/2017 15:18:02success Saved lockfile.
27/12/2017 15:18:02$ opencollective postinstall
27/12/2017 15:18:02
27/12/2017 15:18:02     *** Thank you for using apollo-universal-starter-kit! ***
27/12/2017 15:18:02
27/12/2017 15:18:02Please consider donating to our open collective
27/12/2017 15:18:02     to help us maintain this package.
27/12/2017 15:18:02
27/12/2017 15:18:02  https://opencollective.com/apollo-universal-starter-kit/donate
27/12/2017 15:18:02
27/12/2017 15:18:02                    ***
27/12/2017 15:18:02
27/12/2017 15:18:02Done in 120.68s.
27/12/2017 15:18:02yarn run v1.3.2
27/12/2017 15:18:02$ npm run migrate && knex seed:run
27/12/2017 15:18:03
27/12/2017 15:18:03> apollo-universal-starter-kit@1.0.0 migrate /usr/src/app
27/12/2017 15:18:03> knex migrate:latest
27/12/2017 15:18:03
27/12/2017 15:18:04Using environment: development
27/12/2017 15:18:04Error: Error calling all on connection.
27/12/2017 15:18:04    at /usr/src/app/node_modules/knex/lib/dialects/sqlite3/index.js:141:25
27/12/2017 15:18:04    at Client_SQLite3._query (/usr/src/app/node_modules/knex/lib/dialects/sqlite3/index.js:139:12)
27/12/2017 15:18:04    at Client_SQLite3.query (/usr/src/app/node_modules/knex/lib/client.js:211:17)
27/12/2017 15:18:04    at Runner.<anonymous> (/usr/src/app/node_modules/knex/lib/runner.js:149:36)
27/12/2017 15:18:04From previous event:
27/12/2017 15:18:04    at Runner.queryArray (/usr/src/app/node_modules/knex/lib/runner.js:199:40)
27/12/2017 15:18:04    at /usr/src/app/node_modules/knex/lib/runner.js:59:23
27/12/2017 15:18:04    at runCallback (timers.js:773:18)
27/12/2017 15:18:04    at tryOnImmediate (timers.js:734:5)
27/12/2017 15:18:04From previous event:
27/12/2017 15:18:04    at Runner.run (/usr/src/app/node_modules/knex/lib/runner.js:47:31)
27/12/2017 15:18:04    at SchemaBuilder.Target.then (/usr/src/app/node_modules/knex/lib/interface.js:35:43)
27/12/2017 15:18:04    at Migrator._ensureTable (/usr/src/app/node_modules/knex/lib/migrate/index.js:252:39)
27/12/2017 15:18:04    at Migrator._listCompleted (/usr/src/app/node_modules/knex/lib/migrate/index.js:396:17)
27/12/2017 15:18:04    at Migrator._migrationData (/usr/src/app/node_modules/knex/lib/migrate/index.js:408:58)
27/12/2017 15:18:04    at Migrator.latest (/usr/src/app/node_modules/knex/lib/migrate/index.js:132:17)
27/12/2017 15:18:04    at Command.<anonymous> (/usr/src/app/node_modules/knex/bin/cli.js:127:39)
27/12/2017 15:18:04    at Command.listener (/usr/src/app/node_modules/commander/index.js:315:8)
27/12/2017 15:18:04    at Command.emit (events.js:159:13)
27/12/2017 15:18:04    at Command.parseArgs (/usr/src/app/node_modules/commander/index.js:653:12)
27/12/2017 15:18:04    at Command.parse (/usr/src/app/node_modules/commander/index.js:475:21)
27/12/2017 15:18:04    at Liftoff.invoke (/usr/src/app/node_modules/knex/bin/cli.js:186:13)
27/12/2017 15:18:04    at Liftoff.<anonymous> (/usr/src/app/node_modules/liftoff/index.js:198:16)
27/12/2017 15:18:04    at module.exports (/usr/src/app/node_modules/flagged-respawn/index.js:17:3)
27/12/2017 15:18:04    at Liftoff.<anonymous> (/usr/src/app/node_modules/liftoff/index.js:190:9)
27/12/2017 15:18:04    at /usr/src/app/node_modules/liftoff/index.js:164:9
27/12/2017 15:18:04    at /usr/src/app/node_modules/knex/node_modules/v8flags/index.js:91:14
27/12/2017 15:18:04npm ERR! code ELIFECYCLE
27/12/2017 15:18:04npm ERR! errno 1
27/12/2017 15:18:04npm ERR! apollo-universal-starter-kit@1.0.0 migrate: `knex migrate:latest`
27/12/2017 15:18:04npm ERR! Exit status 1
27/12/2017 15:18:04npm ERR!
27/12/2017 15:18:04npm ERR! Failed at the apollo-universal-starter-kit@1.0.0 migrate script.
27/12/2017 15:18:04npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
27/12/2017 15:18:04
27/12/2017 15:18:04npm ERR! A complete log of this run can be found in:
27/12/2017 15:18:04npm ERR!     /home/node/.npm/_logs/2017-12-27T18_18_04_391Z-debug.log
27/12/2017 15:18:04error Command failed with exit code 1.
27/12/2017 15:18:04info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
or this error inside Shell

```
/usr/src/app $ yarn seed
yarn run v1.3.2
$ npm run migrate && knex seed:run

> apollo-universal-starter-kit@1.0.0 migrate /usr/src/app
> knex migrate:latest

module.js:557
    throw err;
    ^

Error: Cannot find module 'babel-polyfill'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/app/knexfile.js:3:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at initKnex (/usr/src/app/node_modules/knex/bin/cli.js:50:16)
    at Command.<anonymous> (/usr/src/app/node_modules/knex/bin/cli.js:127:17)
    at Command.listener (/usr/src/app/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:159:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! apollo-universal-starter-kit@1.0.0 migrate: `knex migrate:latest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the apollo-universal-starter-kit@1.0.0 migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2017-12-27T19_28_08_091Z-debug.log

```

**Comment by MichelDiz** [comment]
Solved with

```
from node:9.3.0-alpine

RUN apk add --no-cache git
RUN apk add --no-cache --virtual .build-deps \
    ca-certificates \
    wget \
    tar && \
    cd /usr/local/bin && \
    wget https://yarnpkg.com/latest.tar.gz && \
    tar zvxf latest.tar.gz && \
    ln -s /usr/local/bin/dist/bin/yarn.js /usr/local/bin/yarn.js && \
    apk del .build-deps

COPY . /usr/src/app

WORKDIR /usr/src/app

```
