### ISSUE TITLE
On server side render (SSR), GraphQL validates directives (@client, @if), but doesn't on the client.

### ISSUE THREAD

**Issue by adam-s** [sysgears/apollo-universal-starter-kit#611]
In order to use [Apollo Link State](https://github.com/apollographql/apollo-link-state) as the client store -- Redux doesn't need to be a dependency -- GraphQL queries use the @client directive. When the client is rendered on the server for some reason KnownDirectives method at `/apollo-universal-starter-kit/node_modules/graphql/validation/rules/KnownDirectives.js` is called with the query but the @client directive isn't defined. This might be a Apollo Link State issue. However, on the server, it looks like express-apollo is parsing the queries unlike on the client when rendering and it works different from apollo-client.

Here is the repository with the changes `https://github.com/adam-s/apollo-universal-starter-kit/tree/apollo-link-state`.

The error thrown is 
````
backend error { Error: GraphQL error: Cannot query field "getValue" on type "Query".
GraphQL error: Unknown directive "client".
    at new ApolloError (/home/adam/PhpstormProjects/apollo-universal-starter-kit/node_modules/apollo-client/errors/ApolloError.js:34:28)
    at /home/adam/PhpstormProjects/apollo-universal-starter-kit/node_modules/apollo-client/core/QueryManager.js:266:41
    at /home/adam/PhpstormProjects/apollo-universal-starter-kit/node_modules/apollo-client/core/QueryManager.js:646:17
    at Array.forEach (<anonymous>)
    at /home/adam/PhpstormProjects/apollo-universal-starter-kit/node_modules/apollo-client/core/QueryManager.js:645:18
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (/home/adam/PhpstormProjects/apollo-universal-starter-kit/node_modules/apollo-client/core/QueryManager.js:640:22)
    at Object.next (/home/adam/PhpstormProjects/apollo-universal-starter-kit/node_modules/apollo-client/core/QueryManager.js:672:31)
    at SubscriptionObserver.next (/home/adam/PhpstormProjects/apollo-universal-starter-kit/node_modules/zen-observable/zen-observable.js:154:14)
    at /home/adam/PhpstormProjects/apollo-universal-starter-kit/node_modules/apollo-link-dedup/lib/dedupLink.js:49:76
    at Array.forEach (<anonymous>)
    at Object.next (/home/adam/PhpstormProjects/apollo-universal-starter-kit/node_modules/apollo-link-dedup/lib/dedupLink.js:49:43)
    at SubscriptionObserver.next (/home/adam/PhpstormProjects/apollo-universal-starter-kit/node_modules/zen-observable/zen-observable.js:154:14)
    at /home/adam/PhpstormProjects/apollo-universal-starter-kit/node_modules/apollo-link-batch/lib/batching.js:58:37
    at Array.forEach (<anonymous>)
    at Object.next (/home/adam/PhpstormProjects/apollo-universal-starter-kit/node_modules/apollo-link-batch/lib/batching.js:56:25)
  graphQLErrors: 
   [ { message: 'Cannot query field "getValue" on type "Query".',
       locations: [ [Object] ] },
     { message: 'Unknown directive "client".',
       locations: [ [Object] ] } ],
  networkError: null,
  message: 'GraphQL error: Cannot query field "getValue" on type "Query".\nGraphQL error: Unknown directive "client".',
  extraInfo: undefined,
  queryErrors: [ [Circular] ] }
````

**Comment by vlasenko** [comment]
@adam-s You have not configured Apollo Link State on the server side, thats why you have issues with server side rendering. This is all good, but what is has to do with the kit at all?

**Comment by adam-s** [comment]
Ok, I understand now. There are two different files used when bootstrapping a page load, Main.jsx (src/client/app/Main.jsx) and website.jsx (src/server/middleware/website.jsx). They are somewhat similar with a few subtle differences. For documentation sake for newcomers like myself, it should be noted that for server side rendering any changes made in Main.jsx need to also be reflected in website.jsx.

**Comment by vlasenko** [comment]
@adam-s Yes, this is correct
