### ISSUE TITLE
Sequelize error

### ISSUE THREAD

**Issue by wojcikiewiczm** [sysgears/apollo-universal-starter-kit#616]
Hello I'm trying to use sequelize with this starter kit but I'm getting this error

```
webpack-for-webDll ModuleNotFoundError: Module not found: Error: Can't resolve 'dns' in 'C:\Dev\optimit-managingApp\node_modules\tedious\lib'
    at factoryCallback (C:\Dev\optimit-managingApp\node_modules\webpack\lib\Compilation.js:276:40)
    at factory (C:\Dev\optimit-managingApp\node_modules\webpack\lib\NormalModuleFactory.js:235:20)
    at resolver (C:\Dev\optimit-managingApp\node_modules\webpack\lib\NormalModuleFactory.js:60:20)
    at asyncLib.parallel.e (C:\Dev\optimit-managingApp\node_modules\webpack\lib\NormalModuleFactory.js:127:20)
    at C:\Dev\optimit-managingApp\node_modules\async\dist\async.js:3874:9
    at C:\Dev\optimit-managingApp\node_modules\async\dist\async.js:473:16
    at iteratorCallback (C:\Dev\optimit-managingApp\node_modules\async\dist\async.js:1048:13)
    at C:\Dev\optimit-managingApp\node_modules\async\dist\async.js:958:16
    at C:\Dev\optimit-managingApp\node_modules\async\dist\async.js:3871:13
    at resolvers.normal.resolve (C:\Dev\optimit-managingApp\node_modules\webpack\lib\NormalModuleFactory.js:119:22)
```

Also sometimes I'm getting this error by pg module. Thanks

**Comment by vlasenko** [comment]
@wojcikiewiczm Add `"tedious": "server"` into `tools/webpackAppConfig.js -> dependencyPlatforms`, so that kit know this is a server-only package and don't try to compile it for web platform and put into webpack DLL.

**Comment by vlasenko** [comment]
@wojcikiewiczm Also check what packages it tries to put into web DLL and whether there are any server-side packages in this list and if yes add them into `dependencyPlatforms`

**Comment by wojcikiewiczm** [comment]
@vlasenko nice thanks! 👍
