### ISSUE TITLE
Error spawn enoent - windows

### ISSUE THREAD

**Issue by Qeneke** [sysgears/apollo-universal-starter-kit#684]
I get "Error spawn ... ENOENT" error in some processes in windows operating system

**for example:**
> yarn exp-publish output:

```
lerna info version 2.8.0
lerna info versioning independent
lerna info scope mobile
mobile: $ yarn exp-login && yarn exp -- p --non-interactive
mobile: $ cross-env NODE_ENV=production spin exp login -u $EXP_USERNAME -p $EXP_PASSWORD --non-interactive
mobile: spin error { Error: spawn C:\...\packages\mobile\node_modules\.bin\exp ENOENT
mobile:     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
mobile:     at onErrorNT (internal/child_process.js:379:16)
mobile:     at process._tickCallback (internal/process/next_tick.js:114:19)
mobile:     at Function.Module.runMain (module.js:692:11)
mobile:     at startup (bootstrap_node.js:194:16)
mobile:     at bootstrap_node.js:666:3
mobile:   errno: 'ENOENT',
mobile:   code: 'ENOENT',
mobile:   syscall: 'spawn C:\\...\\packages\\mobile\\node_modules\\.bin\\exp',
mobile:   path: 'C:\\...\\packages\\mobile\\node_modules\\.bin\\exp',
mobile:   spawnargs: [ 'login', '-u', '', '-p', '', '--non-interactive' ] }
mobile: warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
mobile: $ cross-env NODE_ENV=production spin exp p --non-interactive
mobile: spin info Starting Expo prod server
mobile: spin info Production mobile packager listening on http://localhost:3030
mobile: spin info Expo server running on address: exp://localhost:19000
mobile: spin error { Error: spawn C:\...\packages\mobile\node_modules\.bin\exp ENOENT
mobile:     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
mobile:     at onErrorNT (internal/child_process.js:379:16)
mobile:     at process._tickCallback (internal/process/next_tick.js:114:19)
mobile:   errno: 'ENOENT',
mobile:   code: 'ENOENT',
mobile:   syscall: 'spawn C:\\...\\packages\\mobile\\node_modules\\.bin\\exp',
mobile:   path: 'C:\\...\\packages\\mobile\\node_modules\\.bin\\exp',
mobile:   spawnargs: [ 'p', '--non-interactive' ] }
```

> yarn test output

```
yarn run v1.3.2
$ yarn tests && yarn lint
$ lerna run tests --stream
lerna info version 2.8.0
lerna info versioning independent
client: $ cross-env NODE_ENV=test PORT=7070 spin test -t 10000 --full-trace --exit "src/**/*.spec.js"
mobile: $ cross-env NODE_ENV=test PORT=7070 spin test -t 10000 --full-trace --exit "src/**/*.spec.js"
server: $ cross-env NODE_ENV=test PORT=7070 spin test -t 10000 --full-trace --exit "src/**/*.spec.js"
mobile: spin info Running C:\...\packages\mobile\node_modules\.bin\mocha-webpack --include babel-polyfill --webpack-config C:\...\node_modules\spinjs\webpack.config.js --include raf/polyfill -t 10000 --full-trace --exit src/**/*.spec.js
server: spin info Running C:\...\packages\server\node_modules\.bin\mocha-webpack --include babel-polyfill --webpack-config C:\...\node_modules\spinjs\webpack.config.js --include raf/polyfill -t 10000 --full-trace --exit src/**/*.spec.js
client: spin info Running C:\...\packages\client\node_modules\.bin\mocha-webpack --include babel-polyfill --webpack-config C:\...\node_modules\spinjs\webpack.config.js --include raf/polyfill -t 10000 --full-trace --exit src/**/*.spec.js
mobile: spin error { Error: spawn C:\...\packages\mobile\node_modules\.bin\mocha-webpack ENOENT
mobile:     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
mobile:     at onErrorNT (internal/child_process.js:379:16)
mobile:     at process._tickCallback (internal/process/next_tick.js:114:19)
mobile:     at Function.Module.runMain (module.js:692:11)
mobile:     at startup (bootstrap_node.js:194:16)
mobile:     at bootstrap_node.js:666:3
mobile:   errno: 'ENOENT',
mobile:   code: 'ENOENT',
mobile:   syscall: 'spawn C:\\...\\packages\\mobile\\node_modules\\.bin\\mocha-webpack',
mobile:   path: 'C:\\...\\packages\\mobile\\node_modules\\.bin\\mocha-webpack',
mobile:   spawnargs:
mobile:    [ '--include',
mobile:      'babel-polyfill',
mobile:      '--webpack-config',
mobile:      'C:\\...\\node_modules\\spinjs\\webpack.config.js',
mobile:      '--include',
mobile:      'raf/polyfill',
mobile:      '-t',
mobile:      '10000',
mobile:      '--full-trace',
mobile:      '--exit',
mobile:      'src/**/*.spec.js' ] }
client: spin error { Error: spawn C:\...\packages\client\node_modules\.bin\mocha-webpack ENOENT
client:     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
client:     at onErrorNT (internal/child_process.js:379:16)
client:     at process._tickCallback (internal/process/next_tick.js:114:19)
client:     at Function.Module.runMain (module.js:692:11)
client:     at startup (bootstrap_node.js:194:16)
client:     at bootstrap_node.js:666:3
client:   errno: 'ENOENT',
client:   code: 'ENOENT',
client:   syscall: 'spawn C:\\...\\packages\\client\\node_modules\\.bin\\mocha-webpack',
client:   path: 'C:\\...\\packages\\client\\node_modules\\.bin\\mocha-webpack',
client:   spawnargs:
client:    [ '--include',
client:      'babel-polyfill',
client:      '--webpack-config',
client:      'C:\\...\\node_modules\\spinjs\\webpack.config.js',
client:      '--include',
client:      'raf/polyfill',
client:      '-t',
client:      '10000',
client:      '--full-trace',
client:      '--exit',
client:      'src/**/*.spec.js' ] }
server: spin error { Error: spawn C:\...\packages\server\node_modules\.bin\mocha-webpack ENOENT
server:     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
server:     at onErrorNT (internal/child_process.js:379:16)
server:     at process._tickCallback (internal/process/next_tick.js:114:19)
server:     at Function.Module.runMain (module.js:692:11)
server:     at startup (bootstrap_node.js:194:16)
server:     at bootstrap_node.js:666:3
server:   errno: 'ENOENT',
server:   code: 'ENOENT',
server:   syscall: 'spawn C:\\...\\packages\\server\\node_modules\\.bin\\mocha-webpack',
server:   path: 'C:\\...\\packages\\server\\node_modules\\.bin\\mocha-webpack',
server:   spawnargs:
server:    [ '--include',
server:      'babel-polyfill',
server:      '--webpack-config',
server:      'C:\\...\\node_modules\\spinjs\\webpack.config.js',
server:      '--include',
server:      'raf/polyfill',
server:      '-t',
server:      '10000',
server:      '--full-trace',
server:      '--exit',
server:      'src/**/*.spec.js' ] }
lerna success run Ran npm script 'tests' in packages:
lerna success - client
lerna success - mobile
lerna success - server
```

**Comment by vlasenko** [comment]
@Qeneke Please add exact reproduction steps.

**Comment by Qeneke** [comment]
spinjs origin
in the spinjs/lib/executor.js file
```
exp = child_process_1.spawn(path.join(process.cwd(), 'node_modules/.bin/exp'), process.argv.splice(expIdx + 1), {
                        cwd: projectRoot,
                        stdio: [0, 1, 2]
                    });
```
cmd file should be used for windows
like this
```
exp = child_process_1.spawn(path.join(process.cwd(), 'node_modules/.bin/exp.cmd'), process.argv.splice(expIdx + 1), {
                        cwd: projectRoot,
                        stdio: [0, 1, 2]
                    });
```
