### ISSUE TITLE
Error when yarn watch is run

### ISSUE THREAD

**Issue by coooolers** [sysgears/apollo-universal-starter-kit#741]
webpack-for-server Spawning node --inspect=9229 /home/cool/Project/apollo-universal-starter-kit/packages/server/build/index.js
Debugger listening on ws://127.0.0.1:9229/0e9cfe04-400f-4dc9-a333-3da73249bb98
For help see https://nodejs.org/en/docs/inspector
TypeError: Pass phrase must be a buffer
    at pbkdf2 (crypto.js:644:20)
    at Object.exports.pbkdf2Sync (crypto.js:629:10)
    at _deriveSymmetricKey (/home/cool/Project/apollo-universal-starter-kit/packages/server/src/modules/user/access/session/crypto.js:5:1)

**Comment by vlasenko** [comment]
@coooolers You should have this line in your `.env` file:
https://github.com/sysgears/apollo-universal-starter-kit/blob/51e5a226dcf36165e670132e43afe07426b280d1/packages/server/.env#L11

**Comment by coooolers** [comment]
Thank you, the error has been resolved. But there is another error:

backend error TypeError: Data must be a string or a buffer
    at Hmac.update (crypto.js:99:16)
    at hmac (/home/cool/Project/apollo-universal-starter-kit/packages/server/src/modules/user/access/session/crypto.js:11:1)

**Comment by vlasenko** [comment]
@coooolers Try to clean cookies in the browser

**Comment by coooolers** [comment]
yes Resolved Thank you
