### ISSUE TITLE
spin error { Error: Cannot find module 'webpack/package.json'

### ISSUE THREAD

**Issue by stumbly** [sysgears/apollo-universal-starter-kit#742]
I'm getting spin errors all of a sudden - any idea as to why this is happening?  
I feel like it's a simple error, but I have spent a lot of time on this now and really need to find an answer asap...

Thanks! 

$ spin watch
spin error { Error: Cannot find module 'webpack/package.json'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at requireRelative (/home/metabot/metatrax_rebuild/node_modules/require-relative/index.js:25:15)
    at requireModule (/home/metabot/metatrax_rebuild/node_modules/spinjs/src/createRequire.ts:21:36)
    at Object.require (/home/metabot/metatrax_rebuild/node_modules/spinjs/src/createRequire.ts:13:52)
    at createConfig (/home/metabot/metatrax_rebuild/node_modules/spinjs/src/plugins/WebpackPlugin.ts:196:30)
    at WebpackPlugin.configure (/home/metabot/metatrax_rebuild/node_modules/spinjs/src/plugins/WebpackPlugin.ts:410:51)
    at /home/metabot/metatrax_rebuild/node_modules/spinjs/src/createConfig.ts:96:62
    at Array.forEach (native) code: 'MODULE_NOT_FOUND' }

**Comment by vlasenko** [comment]
@stumbly Have you tried latest spinjs ?

**Comment by vlasenko** [comment]
@stumbly If you want very quick fix set `spinjs` version in `package.json` to be exactly `0.4.131`, e.g. remove `^` from the version

**Comment by vlasenko** [comment]
@stumbly I think I have broken something starting from spinjs 0.4.132 and higher

**Comment by stumbly** [comment]
Thanks for the fast reply - will try and get back to ya shortly:)

**Comment by stumbly** [comment]
Hmm I'm still seeing the error: 

Here are some env variables: 
node -v
v8.2.1
nodejs -v
v4.2.6
npm -v
6.1.0
yarn -v
1.6.0

**Comment by vlasenko** [comment]
@stumbly These are not relevant. Try to downgrade spinjs version

**Comment by vlasenko** [comment]
@stumbly The kit uses version spinjs@0.4.131 in the master. There is no such error. I suspect that you are using `spinjs@0.4.132` that turned out to has a bug. You should use either `spinjs@0.4.131` or `spinjs@0.4.133`. Your environment doesn't matter it is was a bug in spinjs@0.4.132

**Comment by stumbly** [comment]
Sorry for the late reply - I changed it to 0.4.44 which was last working version I was using, but it seems to be more: 

It seems that when I do the initial "yarn" (after a rm -r node_modules) it doesn't install spinjs or webpack. When  I "yarn list" right after the install, neither is present. So then when I "yarn watch" it complains:

$ spin watch
/bin/sh: 1: spin: not found
error Command failed with exit code 127.

so then I install again "yarn add --dev spinjs@0.4.44" then running it again I get: 

$ spin watch
spin error { Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at requireRelative (/home/metabot/metatrax/node_modules/require-relative/index.js:25:15)
    at Object.requireModule [as default] (/home/metabot/metatrax/node_modules/spinjs/src/requireModule.ts:6:7)
    at createPlugins (/home/metabot/metatrax/node_modules/spinjs/src/plugins/WebpackPlugin.ts:16:32)
    at createConfig (/home/metabot/metatrax/node_modules/spinjs/src/plugins/WebpackPlugin.ts:176:19)
    at WebpackPlugin.configure (/home/metabot/metatrax/node_modules/spinjs/src/plugins/WebpackPlugin.ts:328:51)
    at /home/metabot/metatrax/node_modules/spinjs/src/createConfig.ts:73:61
    at Array.forEach (native) code: 'MODULE_NOT_FOUND' }

Then I reinstall "yarn add --dev webpack@3.8.1" and it goes back to not being able to find yarn. This can go back and forth as many times as I want.... 

Any ideas...?

**Comment by stumbly** [comment]
found the answer incase anyone runs into this again, it seems to be related to yarn itself.
I now have to include the --prod=false flag to get it to install the devDeps into the lockfile....
I tried to see if NODE_ENV was set anywhere in the code but couldn't find it, so not sure why this is happening. Anyway, thanks again for your help @vlasenko
yarn install --production[=true|false]
Yarn will not install any package listed in devDependencies if the NODE_ENV environment variable is set to production. Use this flag to instruct Yarn to ignore NODE_ENV and take its production-or-not status from this flag instead.

**Comment by vlasenko** [comment]
@Tzikas Output from terminal with error that you see would be helpful

**Comment by Tzikas** [comment]
```
$ yarn watch
yarn watch v0.24.6
(node:39199) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ spin watch 
spin error { Error: Cannot find module 'webpack/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at requireRelative (/Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/node_modules/require-relative/index.js:25:15)
    at requireModule (/Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/node_modules/spinjs/src/createRequire.ts:21:36)
    at Object.require (/Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/node_modules/spinjs/src/createRequire.ts:13:52)
    at createConfig (/Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/node_modules/spinjs/src/plugins/WebpackPlugin.ts:197:30)
    at WebpackPlugin.configure (/Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/node_modules/spinjs/src/plugins/WebpackPlugin.ts:414:51)
    at /Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/node_modules/spinjs/src/createConfig.ts:96:62
    at Array.forEach (<anonymous>) code: 'MODULE_NOT_FOUND' }
✨  Done in 0.98s.
```
&&& 

```
$ yarn install --production[=true|false]
-bash: false]: command not found
(node:39203) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:835:14)
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket.stdout._destroy (internal/process/stdio.js:29:7)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:837:10)
```

**Comment by vlasenko** [comment]
@Tzikas 
`yarn install --prod=false`

**Comment by Tzikas** [comment]
I tried that as well and that seemed to be successful, but then yarn watch still threw the same error. 

```
arn install --prod=false
yarn install v0.24.6
(node:39560) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "tslint-plugin-prettier@1.3.0" has unmet peer dependency "prettier@^1.4.0".
warning "eslint-plugin-prettier@2.6.2" has unmet peer dependency "prettier@>= 0.11.0".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
$ opencollective postinstall

     *** Thank you for using apollo-universal-starter-kit! ***

Please consider donating to our open collective
     to help us maintain this package.

  https://opencollective.com/apollo-universal-starter-kit/donate

                    ***

✨  Done in 19.53s.```

```$ yarn watch
yarn watch v0.24.6
(node:39574) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ spin watch 
spin error { Error: Cannot find module 'webpack/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at requireRelative (/Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/node_modules/require-relative/index.js:25:15)
    at requireModule (/Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/node_modules/spinjs/src/createRequire.ts:21:36)
    at Object.require (/Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/node_modules/spinjs/src/createRequire.ts:13:52)
    at createConfig (/Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/node_modules/spinjs/src/plugins/WebpackPlugin.ts:197:30)
    at WebpackPlugin.configure (/Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/node_modules/spinjs/src/plugins/WebpackPlugin.ts:414:51)
    at /Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/node_modules/spinjs/src/createConfig.ts:96:62
    at Array.forEach (<anonymous>) code: 'MODULE_NOT_FOUND' }
✨  Done in 1.02s.
```

**Comment by vlasenko** [comment]
@Tzikas This project uses yarn workspaces. And your version of `yarn` is very outdated. Either update yarn to version >= 1.0.0 or check yarn documentation for your version of `yarn` how to enable yarn workspaces support.

**Comment by Tzikas** [comment]
That worked.  `npm install -g yarn` Thanks!  I'm now getting a blank white screen on localhost:3000 and ```error TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type undefined``` but that's a different issue.
