### ISSUE TITLE
Error on `yarn start` in master branch

### ISSUE THREAD

**Issue by clodal** [sysgears/apollo-universal-starter-kit#824]
Running `yarn start` results in the following error:

```
// console after running `yarn start`
$ lerna run --scope=server start --stream
lerna info version 2.11.0
lerna info versioning independent
lerna info scope server
server: $ node --harmony build
server: Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
server: backend info API is now running on port 8080

// http://localhost:8080
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    at invariant (/Users/joel/Sites/ausk/node_modules/fbjs/lib/invariant.js:42:15)
    at ReactDOMServerRenderer.render (/Users/joel/Sites/ausk/node_modules/react-dom/cjs/react-dom-server.node.development.js:2525:7)
    at ReactDOMServerRenderer.read (/Users/joel/Sites/ausk/node_modules/react-dom/cjs/react-dom-server.node.development.js:2357:19)
    at Object.renderToString (/Users/joel/Sites/ausk/node_modules/react-dom/cjs/react-dom-server.node.development.js:2729:25)
    at /Users/joel/Sites/ausk/packages/server/build/index.js:1:373561
    at /Users/joel/Sites/ausk/packages/server/build/index.js:1:370655
    at Object.next (/Users/joel/Sites/ausk/packages/server/build/index.js:1:370760)
    at o (/Users/joel/Sites/ausk/packages/server/build/index.js:1:369530)
    at <anonymous>
```

<img width="654" alt="screen shot 2018-08-23 at 5 36 30 pm" src="https://user-images.githubusercontent.com/8684825/44517749-1c80b800-a6fb-11e8-9d8b-e3413ee0113e.png">

To reproduce:

```
git clone https://github.com/sysgears/apollo-universal-starter-kit
yarn
yarn seed
yarn build
yarn start
```

### Update
- Error does not happen in `stable` branch

**Comment by vlasenko** [comment]
@clodal This is a bug in `concatenateModules` option implementation in Webpack 4. It has been fixed in Webpack 4.17.1. Going to push fix to upgrade Webpack ver in the master of the kit in 5 mins
