### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type undefined

### ISSUE THREAD

**Issue by Tzikas** [sysgears/apollo-universal-starter-kit#827]
After going through the instructions and running `yarn watch` I get the following: 

```backend info API is now running on port 8080

[at-loader] Checking started in a separate process...
web-webpack debug waiting for tcp:localhost:8080

[at-loader] Ok, 0.608 sec.
web-webpack debug Backend has been started, resuming webpack dev server...
web-webpack debug bundle is now VALID.
web-webpack info Time: 32196ms
backend error TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type undefined
    at Hmac.update (internal/crypto/hash.js:58:11)
    at hmac (/Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/packages/server/src/modules/user/access/session/crypto.js:11:1)
..............
..............
```

**Comment by vlasenko** [comment]
@Tzikas Check that you have this:
https://github.com/sysgears/apollo-universal-starter-kit/blob/master/packages/server/.env#L11

**Comment by Tzikas** [comment]
Hey thanks for the reply, but no it didn't work.  I copied your exact .env file and still received the same error.  


```
[at-loader] Checking started in a separate process...
web-webpack debug waiting for tcp:localhost:8080

[at-loader] Ok, 1.606 sec.
backend info API is now running on port 8080
web-webpack debug Backend has been started, resuming webpack dev server...
web-webpack debug bundle is now VALID.
web-webpack info Time: 34731ms
backend error TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type undefined
    at Hmac.update (internal/crypto/hash.js:58:11)
    at hmac (/Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/packages/server/src/modules/user/access/session/crypto.js:11:1)
    at decryptSession (/Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/packages/server/src/modules/user/access/session/crypto.js:32:1)
    at readSession (/Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/packages/server/src/modules/user/access/session/sessions.js:12:1)
    at attachSession (/Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/packages/server/src/modules/user/access/session/index.js:27:1)
    at /Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/packages/server/src/modules/user/access/session/index.js:66:1
    at Layer.handle [as handle_request] (/Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/node_modules/express/lib/router/index.js:317:13)
    at /Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/node_modules/body-parser/lib/types/json.js:110:7)
    at Layer.handle [as handle_request] (/Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/node_modules/express/lib/router/index.js:317:13)
    at /Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/node_modules/express/lib/router/index.js:335:12)
```

**Comment by vlasenko** [comment]
@Tzikas Have you cloned this repo from `stable` branch or from `master`?

**Comment by Tzikas** [comment]
stable.  I'm trying master now.

**Comment by vlasenko** [comment]
@Tzikas I have just cloned repo from `stable`, followed getting started instructions and I don't have this problem.

**Comment by vlasenko** [comment]
@Tzikas In any case it looks easy, you can follow stack trace and troubleshoot it yourself

**Comment by Tzikas** [comment]
Could it be some dependency that I need to update?

**Comment by Tzikas** [comment]
master gives me the same bug

**Comment by vlasenko** [comment]
@Tzikas You can follow the stack trace it throws at you and then `console.log` inside source code to figure out whats wrong.

**Comment by Tzikas** [comment]
Like inside `/Users/Squirrel/Documents/Code/APOLLO/apollo-universal-starter-kit/packages/server/src/modules/user/access/session/crypto.js:11:1` ?

**Comment by vlasenko** [comment]
Yes

**Comment by vlasenko** [comment]
@Tzikas Have you been able to troubleshoot the issue?
