### ISSUE TITLE
Error: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by coooolers** [sysgears/apollo-universal-starter-kit#835]
1. Login as admin

2. Click Users i.e. browse to this route:
http://localhost:3000/users

3. Click Logout and the system reports this error:

TypeError: Cannot read property 'map' of undefined
renderBody
at packages/server/packages/client/src/modules/common/components/web/ui-bootstrap/components/Table.jsx:16:0

Table
at packages/server/packages/client/src/modules/common/components/web/ui-bootstrap/components/Table.jsx:33:0

**Comment by lgants** [comment]
@coooolers are you still experiencing this issue? I'm unable to recreate in master/stable branches
