### ISSUE TITLE
CLI Error

### ISSUE THREAD

**Issue by Yourdigitalheart** [sysgears/apollo-universal-starter-kit#846]
I am trying to use addmodule but I got error on fresh install:

`yarn cli addmodule Home client
yarn run v1.9.4
$ node tools/cli addmodule Home client
Copying client files…
/Users/sys/Documents/Github/test/tools/cli/module.js:22
  if (mkdir.code === 0) {
            ^

TypeError: Cannot read property 'code' of undefined
    at copyFiles (/Users/sys/Documents/Github/test/tools/cli/module.js:22:13)
    at module.exports (/Users/sys/Documents/Github/test/tools/cli/module.js:131:7)
    at Command.prog.version.command.argument.argument.action [as _action] (/Users/sys/Documents/Github/test/tools/cli.js:14:38)
    at Command._run (/Users/sys/Documents/Github/test/node_modules/caporal/lib/command.js:408:40)
    at Program._run (/Users/sys/Documents/Github/test/node_modules/caporal/lib/program.js:165:16)
    at Program.parse (/Users/sys/Documents/Github/test/node_modules/caporal/lib/program.js:268:17)
    at Object.<anonymous> (/Users/sys/Documents/Github/test/tools/cli.js:25:6)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
error Command failed with exit code 1.`

**Comment by lyzhovnik** [comment]
Hi, thank you for your issue. I checked it and yes, this bug exists. Have you already fixed it?

**Comment by Yourdigitalheart** [comment]
Hi I just switch to Crud-cli and its works fine

**Comment by Yourdigitalheart** [comment]
But I am interested by the main branch :)

**Comment by Yourdigitalheart** [comment]
My configuration 
OSX: 10.13.6
Nvm 9.11.2 
let me know if you need more information

**Comment by lyzhovnik** [comment]
@Yourdigitalheart If you mean this branch https://github.com/sysgears/apollo-universal-starter-kit/pull/524, It's still in progress. Also We have this new one https://github.com/sysgears/apollo-universal-starter-kit/pull/790  - I'll fix this bug and merge this branch into master.

**Comment by Yourdigitalheart** [comment]
Hi @lyzhovnik when do you think you can merge it into master

Thanks

**Comment by lyzhovnik** [comment]
Hi, I’ve made a new branch without crud cli, also fixed bug and updated templates. Today I’ll merge it. Thank you for waiting.

**Comment by lyzhovnik** [comment]
Hi again @Yourdigitalheart . I've fixed and updated the cli . Full info you can see here - https://github.com/sysgears/apollo-universal-starter-kit/pull/847 

Thank you for the issue and waiting.
