### ISSUE TITLE
Error in client../../locales/index.js

### ISSUE THREAD

**Issue by abhayca** [sysgears/apollo-universal-starter-kit#852]
I used the cli tool to generate a module

I got this error when I tried to run yarn watch. The error is reported inside client../customer/locales/index.js  This file is empty. I didn't succeed even when I put this line: export default {};

Type checking in progress...
server-webpack error Module build failed (from /home/abhay/Project/apollo-universal-starter-kit/node_modules/@alienfast/i18next-loader/index.js):
SyntaxError: Unexpected token } in JSON at position 200
    at JSON.parse (<anonymous>)
    at moduleLocalesDirs.forEach (/home/abhay/Project/apollo-universal-starter-kit/node_modules/@alienfast/i18next-loader/index.js:73:32)
    at Array.forEach (<anonymous>)
    at Object.module.exports (/home/abhay/Project/apollo-universal-starter-kit/node_modules/@alienfast/i18next-loader/index.js:47:21)
server-webpack error Module build failed (from /home/abhay/Project/apollo-universal-starter-kit/node_modules/@alienfast/i18next-loader/index.js):
SyntaxError: Unexpected token } in JSON at position 518
    at JSON.parse (<anonymous>)
    at moduleLocalesDirs.forEach (/home/abhay/Project/apollo-universal-starter-kit/node_modules/@alienfast/i18next-loader/index.js:73:32)
    at Array.forEach (<anonymous>)
    at Object.module.exports (/home/abhay/Project/apollo-universal-starter-kit/node_modules/@alienfast/i18next-loader/index.js:47:21)
server-webpack info Time: 1111ms
Built at: 09/17/2018 1:35:10 PM
Entrypoint index [big] = index.js index.48580d968a909f49504b.js.map

ERROR in ./src/modules/customer/locales/index.js
Module build failed (from /home/abhay/Project/apollo-universal-starter-kit/node_modules/@alienfast/i18next-loader/index.js):
SyntaxError: Unexpected token } in JSON at position 200
    at JSON.parse (<anonymous>)
    at moduleLocalesDirs.forEach (/home/abhay/Project/apollo-universal-starter-kit/node_modules/@alienfast/i18next-loader/index.js:73:32)
    at Array.forEach (<anonymous>)
    at Object.module.exports (/home/abhay/Project/apollo-universal-starter-kit/node_modules/@alienfast/i18next-loader/index.js:47:21)
 @ ./src/modules/customer/index.js 11:0-34 49:42-51
 @ ./src/modules/index.ts
 @ ./src/api/subscriptions.ts
 @ ./src/server.js
 @ ./src/index.ts
 @ multi raf/polyfill babel-polyfill webpack/hot/signal.js ./src/index.ts

ERROR in ../client/src/modules/customer/locales/index.js
Module build failed (from /home/abhay/Project/apollo-universal-starter-kit/node_modules/@alienfast/i18next-loader/index.js):
SyntaxError: Unexpected token } in JSON at position 518
    at JSON.parse (<anonymous>)
    at moduleLocalesDirs.forEach (/home/abhay/Project/apollo-universal-starter-kit/node_modules/@alienfast/i18next-loader/index.js:73:32)
    at Array.forEach (<anonymous>)
    at Object.module.exports (/home/abhay/Project/apollo-universal-starter-kit/node_modules/@alienfast/i18next-loader/index.js:47:21)
 @ ../client/src/modules/customer/index.web.jsx 8:0-34 32:42-51
 @ ../client/src/modules/index.js
 @ ./src/middleware/website.tsx
 @ ./src/app.js
 @ ./src/server.js
 @ ./src/index.ts
 @ multi raf/polyfill babel-polyfill webpack/hot/signal.js ./src/index.ts
No type errors found

**Comment by abhayca** [comment]
@lyzhovnik Thank you for your response.

There was an error in the translations.json, extra comma was there. This error has been resolved. Now there is one more error related to JSON in the same folder and I am trying to debug it.

**Comment by lyzhovnik** [comment]
@abhayca Okey, if you have any questions about KIT - feel free to write us!
I am closing this issue.

**Comment by abhayca** [comment]
Server side error: Unexpected end of JSON input

Solution:
src/modules/customer/locales/index.js
Solution: The ru/translations.json was empty. Just add the following line in this file:
{} 

In summary, our JSON file must be strictly valid.
