### ISSUE TITLE
Cannot connect MySQL-Database

### ISSUE THREAD

**Issue by theWeird** [sysgears/apollo-universal-starter-kit#903]
**Describe the bug**
I try to get a configuration for mysql in production with this kit up and running.
Instead I receive the following error: TypeError: Unknown SSL profile ''

**To Reproduce**
Add env-variables for mysql database and a mariadb service to the docker-compose file:

```
    environment:
    - NODE_ENV=production
    - DB_TYPE=mysql
    - DB_HOST=db
    - DB_USER=user
    - DB_PASSWORD=pass
    - DB_DATABASE=mydb
  db:
    image: mariadb
    container_name: db
    volumes:
    - mysql_data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=testadmin
    - MYSQL_DATABASE=mydb
    - MYSQL_USER=user
    - MYSQL_PASSWORD=pass
```

**Expected behavior**
Well, the database seeds and the application runs

**Additional context**

In addition I set the command to run inside the app container to: `command: sh -c 'while sleep 3600; do :; done'`, connected to the container by `docker exec -it apollo_universal_starter sh` and ran yarn and yarn seed by hand.

Error Message: 
```
/usr/src/app $ yarn seed
yarn run v1.3.2
$ lerna run --scope=server seed --stream
lerna notice cli v3.4.1
lerna info versioning independent
lerna info filter [ 'server' ]
lerna info Executing command in 1 package: "yarn run seed"
server: $ yarn migrate && knex seed:run
server: $ knex migrate:latest
server: Using environment: development
server: TypeError: Unknown SSL profile ''
server:     at Function.getSSLProfile (/usr/src/app/node_modules/mysql2/lib/connection_config.js:217:11)
server:     at new ConnectionConfig (/usr/src/app/node_modules/mysql2/lib/connection_config.js:95:24)
server:     at Object.module.exports.createConnection (/usr/src/app/node_modules/mysql2/index.js:8:35)
server:     at /usr/src/app/node_modules/knex/lib/dialects/mysql/index.js:105:37
server:     at Promise._execute (/usr/src/app/node_modules/bluebird/js/release/debuggability.js:303:9)
server:     at Promise._resolveFromExecutor (/usr/src/app/node_modules/bluebird/js/release/promise.js:483:18)
server:     at new Promise (/usr/src/app/node_modules/bluebird/js/release/promise.js:79:10)
server:     at Client_MySQL2.acquireRawConnection (/usr/src/app/node_modules/knex/lib/dialects/mysql/index.js:104:12)
server:     at create (/usr/src/app/node_modules/knex/lib/client.js:283:23)
server:     at tryPromise (/usr/src/app/node_modules/tarn/lib/Pool.js:366:22)
server:     at tryPromise (/usr/src/app/node_modules/tarn/lib/utils.js:57:20)
server:     at Promise (/usr/src/app/node_modules/tarn/lib/Pool.js:366:5)
server:     at new Promise (<anonymous>)
server:     at callbackOrPromise (/usr/src/app/node_modules/tarn/lib/Pool.js:357:10)
server:     at Pool._create (/usr/src/app/node_modules/tarn/lib/Pool.js:307:5)
server:     at Pool._doCreate (/usr/src/app/node_modules/tarn/lib/Pool.js:275:32)
server: error Command failed with exit code 1.
server: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
server: error Command failed with exit code 1.
server: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run seed exited 1 in 'server'
lerna ERR! yarn run seed stdout:
$ yarn migrate && knex seed:run
$ knex migrate:latest
Using environment: development
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run seed stderr:
TypeError: Unknown SSL profile ''
    at Function.getSSLProfile (/usr/src/app/node_modules/mysql2/lib/connection_config.js:217:11)
    at new ConnectionConfig (/usr/src/app/node_modules/mysql2/lib/connection_config.js:95:24)
    at Object.module.exports.createConnection (/usr/src/app/node_modules/mysql2/index.js:8:35)
    at /usr/src/app/node_modules/knex/lib/dialects/mysql/index.js:105:37
    at Promise._execute (/usr/src/app/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/usr/src/app/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/usr/src/app/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL2.acquireRawConnection (/usr/src/app/node_modules/knex/lib/dialects/mysql/index.js:104:12)
    at create (/usr/src/app/node_modules/knex/lib/client.js:283:23)
    at tryPromise (/usr/src/app/node_modules/tarn/lib/Pool.js:366:22)
    at tryPromise (/usr/src/app/node_modules/tarn/lib/utils.js:57:20)
    at Promise (/usr/src/app/node_modules/tarn/lib/Pool.js:366:5)
    at new Promise (<anonymous>)
    at callbackOrPromise (/usr/src/app/node_modules/tarn/lib/Pool.js:357:10)
    at Pool._create (/usr/src/app/node_modules/tarn/lib/Pool.js:307:5)
    at Pool._doCreate (/usr/src/app/node_modules/tarn/lib/Pool.js:275:32)
error Command failed with exit code 1.
error Command failed with exit code 1.

lerna ERR! yarn run seed exited 1 in 'server'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by vlasenko** [comment]
The reproduction steps are invalid. Please provide full reproduction steps
