### ISSUE TITLE
JSON import on frontend dowsn't work

### ISSUE THREAD

**Issue by wojcikiewiczm** [sysgears/apollo-universal-starter-kit#990]
**Describe the bug**
Hello I'm trying to import json file on frontend.
I'm just importing file like this import p from "../locales/en/translations.json";
Version of kit is latest stable (downloaded today)

And getting this error
``ERROR in ../client/src/modules/counter/serverCounter/locales/en/translations.json
Module parse failed: Unexpected token m in JSON at position 0 while parsing near 'module.exports = {}'
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token m in JSON at position 0 while parsing near 'module.exports = {}'
    at JSON.parse (<anonymous>)
    at parseJson (C:\Dev\Devly Engine\NEW\node_modules\json-parse-better-errors\index.js:7:17)
    at JsonParser.parse (C:\Dev\Devly Engine\NEW\node_modules\webpack\lib\JsonParser.js:16:16)
    at doBuild.err (C:\Dev\Devly Engine\NEW\node_modules\webpack\lib\NormalModule.js:445:32)
    at runLoaders (C:\Dev\Devly Engine\NEW\node_modules\webpack\lib\NormalModule.js:327:12)
    at C:\Dev\Devly Engine\NEW\node_modules\loader-runner\lib\LoaderRunner.js:370:3
    at iterateNormalLoaders (C:\Dev\Devly Engine\NEW\node_modules\loader-runner\lib\LoaderRunner.js:211:10)
    at iterateNormalLoaders (C:\Dev\Devly Engine\NEW\node_modules\loader-runner\lib\LoaderRunner.js:218:10)
    at C:\Dev\Devly Engine\NEW\node_modules\loader-runner\lib\LoaderRunner.js:233:3
    at runSyncOrAsync (C:\Dev\Devly Engine\NEW\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\Dev\Devly Engine\NEW\node_modules\loader-runner\lib\LoaderRunner.js:229:2)
    at Array.<anonymous> (C:\Dev\Devly Engine\NEW\node_modules\loader-runner\lib\LoaderRunner.js:202:4)
    at Storage.finished (C:\Dev\Devly Engine\NEW\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:43:16)
    at provider (C:\Dev\Devly Engine\NEW\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:79:9)
    at C:\Dev\Devly Engine\NEW\node_modules\graceful-fs\graceful-fs.js:78:16``

**Desktop:**
 - OS: Windows 10

**Comment by vlasenko** [comment]
@wojcikiewiczm You cannot import translation json files directly, because we are using i18next-loader which handles them, read docs please on this loader:
https://github.com/alienfast/i18next-loader
But you can access contents of these json files either through i18n, or by examinig `resources` object, read the docs on i18next-loader

**Comment by wojcikiewiczm** [comment]
Oh okay... Had no idea about that. Thank you 👍
